# Generated by Django 6.1 on 2026-08-31 04:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(help_text='e.g. A, B, C', max_length=5)),
                ('question_number', models.PositiveSmallIntegerField()),
                ('part', models.CharField(blank=True, help_text='e.g. (a), (b)', max_length=3)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT', 'Short Answer'), ('DESC', 'Descriptive'), ('DRAW', 'Diagram / Derivation'), ('NUM', 'Numerical Problem')], default='DESC', max_length=10)),
                ('text_content', models.TextField(help_text='Plain text version of the question')),
                ('latex_content', models.TextField(blank=True, help_text='LaTeX-formatted version for mathematical questions')),
                ('marks', models.PositiveSmallIntegerField()),
                ('co_tag', models.CharField(help_text='e.g. CO3', max_length=10)),
                ('bloom_level', models.CharField(choices=[('REMEMBER', 'Remember (L1)'), ('UNDERSTAND', 'Understand (L2)'), ('APPLY', 'Apply (L3)'), ('ANALYZE', 'Analyze (L4)'), ('EVALUATE', 'Evaluate (L5)'), ('CREATE', 'Create (L6)')], max_length=15)),
                ('is_optional', models.BooleanField(default=False, help_text='True if the student can choose between this and another question')),
            ],
            options={
                'db_table': 'vault_question',
                'ordering': ['section', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='AnswerRubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rubric_text', models.TextField(help_text='Detailed model answer / scheme of evaluation')),
                ('key_points', models.JSONField(default=list, help_text='List of key points with individual mark weights')),
                ('max_marks', models.PositiveSmallIntegerField()),
                ('s3_path', models.CharField(blank=True, help_text='Optional S3 path to a handwritten/scanned rubric image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='vault.question')),
            ],
            options={
                'db_table': 'vault_answer_rubric',
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setter_access_token', models.UUIDField(default=uuid.uuid4, help_text='Time-expiring token issued by Dean to grant setter access')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text="When the setter's authoring token expires", null=True)),
                ('title', models.CharField(max_length=300)),
                ('total_marks', models.PositiveSmallIntegerField(default=100)),
                ('duration_mins', models.PositiveSmallIntegerField(default=180)),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('MIXED', 'Mixed')], default='MIXED', max_length=10)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft – Being Authored'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved by CoE'), ('REJECTED', 'Rejected – Needs Revision'), ('ENCRYPTED', 'Encrypted & Locked in Vault'), ('DISTRIBUTED', 'AES Key Distributed')], db_index=True, default='DRAFT', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('ipfs_cid', models.CharField(blank=True, help_text='IPFS Content Identifier for the AES-256-GCM encrypted PDF blob', max_length=500)),
                ('aes_key_hash', models.CharField(blank=True, help_text='SHA-256 hash of the AES key', max_length=128)),
                ('encrypted_aes_key', models.BinaryField(blank=True, help_text='Symmetrically encrypted AES key (unlocked only by backend master key/HSM)', null=True)),
                ('key_unlock_timestamp', models.DateTimeField(blank=True, help_text='UTC time when AES key is automatically released', null=True)),
                ('key_distributed_at', models.DateTimeField(blank=True, null=True)),
                ('co_coverage', models.JSONField(default=dict, help_text="Dict mapping CO codes to marks covered, e.g. {'CO1':20,'CO2':30}")),
                ('bloom_distribution', models.JSONField(default=dict, help_text="Bloom's taxonomy marks distribution, e.g. {'REMEMBER':10,'UNDERSTAND':30}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'CHIEF_SUPERINTENDENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_papers', to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_papers', to='scheduling.examsession')),
                ('setter', models.ForeignKey(limit_choices_to={'role': 'PAPER_SETTER'}, on_delete=django.db.models.deletion.PROTECT, related_name='authored_papers', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_papers', to='scheduling.subject')),
            ],
            options={
                'verbose_name': 'Question Paper',
                'verbose_name_plural': 'Question Papers',
                'db_table': 'vault_question_paper',
                'ordering': ['-created_at'],
                'unique_together': {('subject', 'exam_session')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vault.questionpaper'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_paper', 'section', 'question_number', 'part')},
        ),
    ]
