import { ValuationBundle, ScannedAnswerBooklet, ValuationLedgerEntry } from './types';

export const INITIAL_BUNDLES: ValuationBundle[] = [
  {
    id: 'BUNDLE-CS201-04',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    semester: '3rd Semester B.Tech',
    valuationCenter: 'Central Valuation Center - Block B, Terminal 14',
    totalScripts: 40,
    completedScripts: 28,
    remunerationPerScript: 35,
    deadline: 'Sep 05, 2026',
  },
  {
    id: 'BUNDLE-CS301-02',
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems',
    semester: '5th Semester B.Tech',
    valuationCenter: 'Central Valuation Center - Block B, Terminal 14',
    totalScripts: 35,
    completedScripts: 12,
    remunerationPerScript: 35,
    deadline: 'Sep 08, 2026',
  },
];

export const INITIAL_SCRIPTS: ScannedAnswerBooklet[] = [
  {
    id: 'SCR_8942',
    dummyBarcode: 'ANON-CS201-8942',
    bundleId: 'BUNDLE-CS201-04',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    semester: '3rd Semester B.Tech',
    totalPages: 8,
    status: 'IN_PROGRESS',
    evaluatorTotalScore: 42,
    aiTotalScore: 44,
    maxMarks: 100,
    assignedDate: '2026-08-30',
    questions: [
      {
        id: 'q1',
        questionNumber: 1,
        section: 'Part A',
        statement: 'Explain the difference between linear and non-linear data structures with appropriate examples.',
        maxMarks: 5,
        evaluatorScore: 5,
        aiSuggestedScore: 5,
        aiConfidence: 98,
        aiStepAnalysis: [
          'Step 1: Definition of Linear DS (Array/Stack/Queue) identified (+2 Marks)',
          'Step 2: Definition of Non-Linear DS (Tree/Graph) identified (+2 Marks)',
          'Step 3: Memory traversal distinction clearly articulated (+1 Mark)',
        ],
        schemeOfEvaluation: 'Linear definition (2M), Non-linear definition (2M), Distinction/Examples (1M).',
        modelAnswerSummary: 'Linear structures store elements sequentially with single traversal path (Array, Linked List). Non-linear store hierarchically with multiple traversal routes (Binary Tree, Graph).',
        evaluatorNotes: 'Precise definitions and neat tabular difference.',
        isValued: true,
      },
      {
        id: 'q2',
        questionNumber: 2,
        section: 'Part A',
        statement: 'Write an algorithm to evaluate a postfix expression using an array-based stack.',
        maxMarks: 5,
        evaluatorScore: 4,
        aiSuggestedScore: 4,
        aiConfidence: 94,
        aiStepAnalysis: [
          'Step 1: Operand push mechanism correctly stated (+2 Marks)',
          'Step 2: Operator pop 2 operands and apply calculation (+2 Marks)',
          'Minor syntax omission in division by zero error handling (-1 Mark)',
        ],
        schemeOfEvaluation: 'Stack initialization (1M), Push/Pop logic (2M), Operator evaluation loop (2M).',
        modelAnswerSummary: 'Scan left-to-right. Push operands to stack. On operator, pop op2 and op1, evaluate result = op1 (op) op2, and push result back. Final stack top is answer.',
        evaluatorNotes: 'Good implementation, missed corner case check.',
        isValued: true,
      },
      {
        id: 'q3',
        questionNumber: 3,
        section: 'Part B',
        statement: 'Construct an AVL tree by inserting the following keys sequentially: 30, 20, 40, 10, 25, 28, 50. Show balance factors and rotations at each step.',
        maxMarks: 10,
        evaluatorScore: 8,
        aiSuggestedScore: 9,
        aiConfidence: 92,
        aiStepAnalysis: [
          'Step 1: Insertions 30, 20, 40, 10, 25 correct without imbalance (+4 Marks)',
          'Step 2: Insertion of 28 creates LR imbalance at node 20 (+2 Marks)',
          'Step 3: Double rotation (Left on 25, Right on 20) correctly performed (+3 Marks)',
          'Step 4: Final insertion of 50 balanced (+1 Mark)',
        ],
        schemeOfEvaluation: 'Initial BST tree (3M), Detection of balance factor violation (2M), Correct rotation execution (3M), Final AVL structure (2M).',
        modelAnswerSummary: 'Insert keys in order. On inserting 28, node 20 balance factor becomes -2 (LR case). Perform left rotation on left child (25) followed by right rotation on unbalanced parent (20). Final balanced root: 30.',
        isValued: true,
      },
      {
        id: 'q4',
        questionNumber: 4,
        section: 'Part B',
        statement: 'Describe the working of Dijkstra’s Single Source Shortest Path algorithm with a labeled graph and priority queue implementation. Analyze its time complexity.',
        maxMarks: 10,
        evaluatorScore: null,
        aiSuggestedScore: 8,
        aiConfidence: 95,
        aiStepAnalysis: [
          'Step 1: Distance array initialization (dist[s]=0, dist[v]=inf) (+2 Marks)',
          'Step 2: Min-Heap / Priority Queue relaxation loop verified (+4 Marks)',
          'Step 3: Graph walkthrough diagram matched (+2 Marks)',
          'Step 4: Time complexity O((V+E) log V) derived (+2 Marks)',
        ],
        schemeOfEvaluation: 'Algorithm principle & initialization (3M), Edge relaxation logic (3M), Working example walkthrough (2M), Complexity analysis (2M).',
        modelAnswerSummary: 'Greedy approach maintaining dist[] array and min-priority queue of unvisited vertices. In each iteration, extract min distance u, for each neighbor v relax dist[v] = min(dist[v], dist[u] + weight(u,v)). Time complexity O((V + E) log V).',
        isValued: false,
      },
      {
        id: 'q5',
        questionNumber: 5,
        section: 'Part C',
        statement: 'Explain the 0/1 Knapsack problem using dynamic programming. Formulate the recurrence relation and construct the DP table for weights [2, 3, 4, 5], values [3, 4, 5, 6], and capacity W = 5.',
        maxMarks: 10,
        evaluatorScore: null,
        aiSuggestedScore: 9,
        aiConfidence: 96,
        aiStepAnalysis: [
          'Step 1: Optimal substructure & overlapping subproblems identified (+2 Marks)',
          'Step 2: Recurrence relation K[i,w] = max(K[i-1,w], val[i-1] + K[i-1, w-wt[i-1]]) formulated (+3 Marks)',
          'Step 3: DP matrix filled correctly with optimal profit 7 (+4 Marks)',
        ],
        schemeOfEvaluation: 'Recurrence equation (3M), DP table construction (4M), Optimal subset traceback (3M).',
        modelAnswerSummary: 'DP matrix dimensions (n+1) x (W+1). Max value for capacity 5 is 7 (items with weight 2 and 3).',
        isValued: false,
      },
    ],
    annotations: [
      { id: 'ann_1', pageNumber: 1, type: 'TICK', x: 78, y: 22 },
      { id: 'ann_2', pageNumber: 1, type: 'STEP_MARK', x: 84, y: 28, marksValue: 5 },
      { id: 'ann_3', pageNumber: 2, type: 'TICK', x: 80, y: 45 },
      { id: 'ann_4', pageNumber: 2, type: 'STEP_MARK', x: 84, y: 52, marksValue: 4 },
      { id: 'ann_5', pageNumber: 3, type: 'TICK', x: 82, y: 70 },
      { id: 'ann_6', pageNumber: 3, type: 'STEP_MARK', x: 85, y: 78, marksValue: 8 },
    ],
  },
  {
    id: 'SCR_8943',
    dummyBarcode: 'ANON-CS201-8943',
    bundleId: 'BUNDLE-CS201-04',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    semester: '3rd Semester B.Tech',
    totalPages: 8,
    status: 'VALUED',
    evaluatorTotalScore: 84,
    aiTotalScore: 86,
    maxMarks: 100,
    assignedDate: '2026-08-30',
    valuedDate: '2026-08-31 14:20 IST',
    questions: [],
    annotations: [],
  },
  {
    id: 'SCR_8944',
    dummyBarcode: 'ANON-CS201-8944',
    bundleId: 'BUNDLE-CS201-04',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    semester: '3rd Semester B.Tech',
    totalPages: 6,
    status: 'DEVIATION_FLAGGED',
    evaluatorTotalScore: 62,
    aiTotalScore: 81,
    maxMarks: 100,
    deviationPercent: 19.0,
    assignedDate: '2026-08-30',
    valuedDate: '2026-08-31 15:45 IST',
    questions: [],
    annotations: [],
  },
  {
    id: 'SCR_8945',
    dummyBarcode: 'ANON-CS201-8945',
    bundleId: 'BUNDLE-CS201-04',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    semester: '3rd Semester B.Tech',
    totalPages: 8,
    status: 'PENDING',
    evaluatorTotalScore: null,
    aiTotalScore: 78,
    maxMarks: 100,
    assignedDate: '2026-08-30',
    questions: [],
    annotations: [],
  },
];

export const INITIAL_VALUATION_LEDGER: ValuationLedgerEntry[] = [
  {
    id: 'LEDGER_001',
    scriptDummyBarcode: 'ANON-CS201-8940',
    subjectCode: 'CS201',
    valuedAt: '2026-08-31 11:20 IST',
    totalMarksAwarded: 91,
    maxMarks: 100,
    remunerationEarned: 35,
    digitalSignatureHash: '0x7f9a2b84c3e108d9fa613e54b1a8c9027f54e12c',
  },
  {
    id: 'LEDGER_002',
    scriptDummyBarcode: 'ANON-CS201-8941',
    subjectCode: 'CS201',
    valuedAt: '2026-08-31 12:45 IST',
    totalMarksAwarded: 76,
    maxMarks: 100,
    remunerationEarned: 35,
    digitalSignatureHash: '0x3c81e9b204f7a61d85c2b09e8471da3f6192a5c4',
  },
  {
    id: 'LEDGER_003',
    scriptDummyBarcode: 'ANON-CS201-8943',
    subjectCode: 'CS201',
    valuedAt: '2026-08-31 14:20 IST',
    totalMarksAwarded: 84,
    maxMarks: 100,
    remunerationEarned: 35,
    digitalSignatureHash: '0x9a4f2187c53d109e2b86fa04c178e932b7194f28',
  },
];
