import {
  StudentEligibilityRecord,
  HallTicketRecord,
  FacultyNomination,
  CIEMarksSheet,
  CourseRecord,
  FacultyMember,
  CIEQuestionPaper,
  DepartmentExamSession,
  ExamHall,
  AllocatedSeat,
  FacultyDutyAllocation,
  AISeatingSchedulePlan
} from './types';

export const INITIAL_STUDENTS: StudentEligibilityRecord[] = [
  // ── 3rd Semester Students ──
  {
    id: 'std_1',
    usn: '1RV23CS001',
    name: 'Aarav Sharma',
    email: 'aarav.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    facultyInCharge: 'Prof. Alan Turing',
    attendancePercent: 92.5,
    totalClassesHeld: 80,
    classesAttended: 74,
    cieMarksAvg: 44.5,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
    hallTicketNumber: 'HT-FALL26-CS-001',
  },
  {
    id: 'std_1b',
    usn: '1RV23CS001',
    name: 'Aarav Sharma',
    email: 'aarav.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS203',
    subjectTitle: 'Discrete Mathematics & Graph Theory',
    facultyInCharge: 'Dr. John von Neumann',
    attendancePercent: 88.0,
    totalClassesHeld: 75,
    classesAttended: 66,
    cieMarksAvg: 42.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
  },
  {
    id: 'std_2',
    usn: '1RV23CS002',
    name: 'Ananya Deshmukh',
    email: 'ananya.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    facultyInCharge: 'Prof. Alan Turing',
    attendancePercent: 88.0,
    totalClassesHeld: 80,
    classesAttended: 70,
    cieMarksAvg: 46.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
    hallTicketNumber: 'HT-FALL26-CS-002',
  },
  {
    id: 'std_2b',
    usn: '1RV23CS002',
    name: 'Ananya Deshmukh',
    email: 'ananya.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS203',
    subjectTitle: 'Discrete Mathematics & Graph Theory',
    facultyInCharge: 'Dr. John von Neumann',
    attendancePercent: 94.0,
    totalClassesHeld: 75,
    classesAttended: 71,
    cieMarksAvg: 48.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
  },
  {
    id: 'std_3',
    usn: '1RV23CS003',
    name: 'Rohan Verma',
    email: 'rohan.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    facultyInCharge: 'Prof. Alan Turing',
    attendancePercent: 68.5,
    totalClassesHeld: 80,
    classesAttended: 55,
    cieMarksAvg: 38.0,
    status: 'CONDONABLE',
    hasFeeDues: false,
    condonationReason: 'Represented University in Inter-Collegiate ACM-ICPC Coding Regional Finals (Medical & Attendance waiver requested).',
    condonationApproved: false,
    hallTicketIssued: false,
  },
  {
    id: 'std_3b',
    usn: '1RV23CS003',
    name: 'Rohan Verma',
    email: 'rohan.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS203',
    subjectTitle: 'Discrete Mathematics & Graph Theory',
    facultyInCharge: 'Dr. John von Neumann',
    attendancePercent: 77.0,
    totalClassesHeld: 75,
    classesAttended: 58,
    cieMarksAvg: 36.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: false,
  },
  {
    id: 'std_4',
    usn: '1RV23CS004',
    name: 'Pooja Hegde',
    email: 'pooja.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    facultyInCharge: 'Prof. Alan Turing',
    attendancePercent: 54.0,
    totalClassesHeld: 80,
    classesAttended: 43,
    cieMarksAvg: 22.0,
    status: 'DETAINED',
    hasFeeDues: false,
    hallTicketIssued: false,
  },
  {
    id: 'std_5',
    usn: '1RV23CS005',
    name: 'Vikramaditya Rao',
    email: 'vikram.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    facultyInCharge: 'Prof. Alan Turing',
    attendancePercent: 82.0,
    totalClassesHeld: 80,
    classesAttended: 66,
    cieMarksAvg: 41.0,
    status: 'FEE_BLOCKED',
    hasFeeDues: true,
    dueAmount: '₹18,500 ($220 USD)',
    hallTicketIssued: false,
  },

  // ── 5th Semester Students ──
  {
    id: 'std_6',
    usn: '1RV22CS045',
    name: 'Diya Nambiar',
    email: 'diya.cs22@rvce.edu.in',
    semester: '5th Sem',
    department: 'Computer Science',
    section: 'B',
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems & Kernel Design',
    facultyInCharge: 'Dr. Barbara Liskov',
    attendancePercent: 95.0,
    totalClassesHeld: 76,
    classesAttended: 72,
    cieMarksAvg: 48.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
    hallTicketNumber: 'HT-FALL26-CS-045',
  },
  {
    id: 'std_6b',
    usn: '1RV22CS045',
    name: 'Diya Nambiar',
    email: 'diya.cs22@rvce.edu.in',
    semester: '5th Sem',
    department: 'Computer Science',
    section: 'B',
    subjectCode: 'CS302',
    subjectTitle: 'Database Management Systems',
    facultyInCharge: 'Dr. Edgar Codd',
    attendancePercent: 91.0,
    totalClassesHeld: 74,
    classesAttended: 67,
    cieMarksAvg: 45.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
  },
  {
    id: 'std_7',
    usn: '1RV22CS048',
    name: 'Kabir Mehta',
    email: 'kabir.cs22@rvce.edu.in',
    semester: '5th Sem',
    department: 'Computer Science',
    section: 'B',
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems & Kernel Design',
    facultyInCharge: 'Dr. Barbara Liskov',
    attendancePercent: 71.0,
    totalClassesHeld: 76,
    classesAttended: 54,
    cieMarksAvg: 35.5,
    status: 'CONDONABLE',
    hasFeeDues: false,
    condonationReason: 'Hospitalization for Dengue Fever (Medical Certificate verified by University Health Officer).',
    condonationApproved: true,
    hallTicketIssued: true,
    hallTicketNumber: 'HT-FALL26-CS-048',
  },
  {
    id: 'std_7b',
    usn: '1RV22CS048',
    name: 'Kabir Mehta',
    email: 'kabir.cs22@rvce.edu.in',
    semester: '5th Sem',
    department: 'Computer Science',
    section: 'B',
    subjectCode: 'CS302',
    subjectTitle: 'Database Management Systems',
    facultyInCharge: 'Dr. Edgar Codd',
    attendancePercent: 58.0,
    totalClassesHeld: 74,
    classesAttended: 43,
    cieMarksAvg: 24.0,
    status: 'DETAINED',
    hasFeeDues: false,
    hallTicketIssued: false,
  },

  // ── 7th Semester Students ──
  {
    id: 'std_8',
    usn: '1RV21CS089',
    name: 'Siddharth Pillai',
    email: 'siddharth.cs21@rvce.edu.in',
    semester: '7th Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS401',
    subjectTitle: 'Distributed Systems & Cloud Computing',
    facultyInCharge: 'Dr. Leslie Lamport',
    attendancePercent: 86.5,
    totalClassesHeld: 70,
    classesAttended: 61,
    cieMarksAvg: 45.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
    hallTicketNumber: 'HT-FALL26-CS-089',
  },
  {
    id: 'std_9',
    usn: '1RV21CS092',
    name: 'Tanvi Kulkarni',
    email: 'tanvi.cs21@rvce.edu.in',
    semester: '7th Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS401',
    subjectTitle: 'Distributed Systems & Cloud Computing',
    facultyInCharge: 'Dr. Leslie Lamport',
    attendancePercent: 94.0,
    totalClassesHeld: 70,
    classesAttended: 66,
    cieMarksAvg: 47.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
  },
  {
    id: 'std_10',
    usn: '1RV21CS095',
    name: 'Aditya Sen',
    email: 'aditya.cs21@rvce.edu.in',
    semester: '7th Sem',
    department: 'Computer Science',
    section: 'A',
    subjectCode: 'CS402',
    subjectTitle: 'Artificial Intelligence & Machine Learning',
    facultyInCharge: 'Prof. Geoffrey Hinton',
    attendancePercent: 67.0,
    totalClassesHeld: 72,
    classesAttended: 48,
    cieMarksAvg: 34.0,
    status: 'CONDONABLE',
    hasFeeDues: false,
    condonationReason: 'Medical Leave due to fractured wrist during inter-college athletics.',
    condonationApproved: false,
    hallTicketIssued: false,
  }
];

export const INITIAL_HALL_TICKETS: HallTicketRecord[] = [
  {
    id: 'ht_1',
    ticketNumber: 'HT-CIE1-FALL26-CS-001',
    usn: '1RV23CS001',
    studentName: 'Aarav Sharma',
    semester: '3rd Semester B.Tech',
    department: 'Department of Computer Science & Engineering',
    examSession: 'Fall 2026 Continuous Internal Evaluation - 1 (CIE-1)',
    examCycle: 'CIE-1',
    generatedAt: '2026-08-30 11:30 IST',
    isRevoked: false,
    qrPayload: 'NEXAI_ADMIT_VERIFIED_1RV23CS001_HT-CIE1-FALL26-CS-001_SIGN_HOD_CSE_OK',
    slots: [
      { subjectCode: 'CS201', subjectTitle: 'Data Structures & Algorithms', examDate: 'Oct 15, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-01' },
      { subjectCode: 'MA201', subjectTitle: 'Discrete Mathematical Structures', examDate: 'Oct 18, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-01' },
      { subjectCode: 'CS202', subjectTitle: 'Digital Logic & Microprocessors', examDate: 'Oct 21, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-102', deskNumber: 'D-14' },
      { subjectCode: 'EC205', subjectTitle: 'Analog Electronics Circuits', examDate: 'Oct 24, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-01' },
    ],
  },
  {
    id: 'ht_2',
    ticketNumber: 'HT-CIE1-FALL26-CS-002',
    usn: '1RV23CS002',
    studentName: 'Ananya Deshmukh',
    semester: '3rd Semester B.Tech',
    department: 'Department of Computer Science & Engineering',
    examSession: 'Fall 2026 Continuous Internal Evaluation - 1 (CIE-1)',
    examCycle: 'CIE-1',
    generatedAt: '2026-08-30 11:30 IST',
    isRevoked: false,
    qrPayload: 'NEXAI_ADMIT_VERIFIED_1RV23CS002_HT-CIE1-FALL26-CS-002_SIGN_HOD_CSE_OK',
    slots: [
      { subjectCode: 'CS201', subjectTitle: 'Data Structures & Algorithms', examDate: 'Oct 15, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-02' },
      { subjectCode: 'MA201', subjectTitle: 'Discrete Mathematical Structures', examDate: 'Oct 18, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-02' },
      { subjectCode: 'CS202', subjectTitle: 'Digital Logic & Microprocessors', examDate: 'Oct 21, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-102', deskNumber: 'D-15' },
      { subjectCode: 'EC205', subjectTitle: 'Analog Electronics Circuits', examDate: 'Oct 24, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-02' },
    ],
  },
  {
    id: 'ht_3',
    ticketNumber: 'HT-CIE2-FALL26-CS-045',
    usn: '1RV22CS045',
    studentName: 'Diya Nambiar',
    semester: '5th Semester B.Tech',
    department: 'Department of Computer Science & Engineering',
    examSession: 'Fall 2026 Continuous Internal Evaluation - 2 (CIE-2)',
    examCycle: 'CIE-2',
    generatedAt: '2026-08-30 12:15 IST',
    isRevoked: false,
    qrPayload: 'NEXAI_ADMIT_VERIFIED_1RV22CS045_HT-CIE2-FALL26-CS-045_SIGN_HOD_CSE_OK',
    slots: [
      { subjectCode: 'CS301', subjectTitle: 'Operating Systems', examDate: 'Oct 16, 2026', examTime: '02:00 PM - 05:00 PM', roomAllocated: 'Hall B-201', deskNumber: 'D-10' },
      { subjectCode: 'CS302', subjectTitle: 'Database Management Systems', examDate: 'Oct 19, 2026', examTime: '02:00 PM - 05:00 PM', roomAllocated: 'Hall B-201', deskNumber: 'D-10' },
      { subjectCode: 'CS303', subjectTitle: 'Computer Networks', examDate: 'Oct 22, 2026', examTime: '02:00 PM - 05:00 PM', roomAllocated: 'Hall B-202', deskNumber: 'D-05' },
    ],
  },
  {
    id: 'ht_4',
    ticketNumber: 'HT-CIE2-FALL26-CS-048',
    usn: '1RV22CS048',
    studentName: 'Kabir Mehta',
    semester: '5th Semester B.Tech',
    department: 'Department of Computer Science & Engineering',
    examSession: 'Fall 2026 Continuous Internal Evaluation - 2 (CIE-2)',
    examCycle: 'CIE-2',
    generatedAt: '2026-08-30 12:45 IST',
    isRevoked: false,
    qrPayload: 'NEXAI_ADMIT_VERIFIED_1RV22CS048_HT-CIE2-FALL26-CS-048_SIGN_HOD_CSE_OK',
    slots: [
      { subjectCode: 'CS301', subjectTitle: 'Operating Systems & Kernel Design', examDate: 'Oct 16, 2026', examTime: '02:00 PM - 05:00 PM', roomAllocated: 'Hall B-201', deskNumber: 'D-11' },
      { subjectCode: 'CS302', subjectTitle: 'Database Management Systems', examDate: 'Oct 19, 2026', examTime: '02:00 PM - 05:00 PM', roomAllocated: 'Hall B-201', deskNumber: 'D-11' },
    ],
  },
  {
    id: 'ht_5',
    ticketNumber: 'HT-SEE-FALL26-CS-089',
    usn: '1RV21CS089',
    studentName: 'Siddharth Pillai',
    semester: '7th Semester B.Tech',
    department: 'Department of Computer Science & Engineering',
    examSession: 'Fall Semester End Examination (SEE) 2026',
    examCycle: 'SEE_FINAL',
    generatedAt: '2026-08-30 13:00 IST',
    isRevoked: false,
    qrPayload: 'NEXAI_ADMIT_VERIFIED_1RV21CS089_HT-SEE-FALL26-CS-089_SIGN_HOD_CSE_OK',
    slots: [
      { subjectCode: 'CS401', subjectTitle: 'Distributed Systems & Cloud Computing', examDate: 'Oct 17, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall C-301', deskNumber: 'D-08' },
      { subjectCode: 'CS402', subjectTitle: 'Artificial Intelligence & Machine Learning', examDate: 'Oct 20, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall C-301', deskNumber: 'D-08' },
    ],
  },
];

export const INITIAL_FACULTY_NOMINATIONS: FacultyNomination[] = [
  {
    id: 'fn_1',
    facultyId: 'FAC_104',
    name: 'Dr. Alan Turing',
    designation: 'Professor & Head of Computing',
    email: 'alan.turing@univ.edu',
    phone: '+91 98450 12345',
    experienceYears: 18,
    assignedRole: 'SETTER',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    status: 'ACCEPTED',
  },
  {
    id: 'fn_2',
    facultyId: 'FAC_108',
    name: 'Dr. Barbara Liskov',
    designation: 'Associate Professor',
    email: 'b.liskov@univ.edu',
    phone: '+91 98450 23456',
    experienceYears: 12,
    assignedRole: 'SETTER',
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems',
    status: 'ACCEPTED',
  },
  {
    id: 'fn_3',
    facultyId: 'FAC_112',
    name: 'Prof. Donald Knuth',
    designation: 'Visiting Emeritus Professor',
    email: 'd.knuth@univ.edu',
    phone: '+91 98450 34567',
    experienceYears: 25,
    assignedRole: 'EVALUATOR',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    status: 'NOMINATED',
  },
  {
    id: 'fn_4',
    facultyId: 'FAC_119',
    name: 'Dr. Edsger Dijkstra',
    designation: 'Professor of Algorithms',
    email: 'e.dijkstra@univ.edu',
    phone: '+91 98450 45678',
    experienceYears: 20,
    assignedRole: 'CHIEF_INVIGILATOR',
    subjectCode: 'EXAM_FALL2026',
    subjectTitle: 'Main Examination Block A',
    status: 'ACCEPTED',
  },
];

export const INITIAL_CIE_SHEETS: CIEMarksSheet[] = [
  {
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    semester: '3rd Semester B.Tech',
    facultyInCharge: 'Dr. Alan Turing',
    totalStudents: 120,
    averageScore: 41.2,
    maxMarks: 50,
    isEndorsedByHOD: true,
    endorsedAt: '2026-08-29 16:30 IST',
  },
  {
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems',
    semester: '5th Semester B.Tech',
    facultyInCharge: 'Dr. Barbara Liskov',
    totalStudents: 115,
    averageScore: 43.8,
    maxMarks: 50,
    isEndorsedByHOD: true,
    endorsedAt: '2026-08-30 14:15 IST',
  },
  {
    subjectCode: 'CS302',
    subjectTitle: 'Database Management Systems',
    semester: '5th Semester B.Tech',
    facultyInCharge: 'Dr. Codd',
    totalStudents: 115,
    averageScore: 39.5,
    maxMarks: 50,
    isEndorsedByHOD: false,
  },
  {
    subjectCode: 'CS401',
    subjectTitle: 'Distributed Systems & Cloud Computing',
    semester: '7th Semester B.Tech',
    facultyInCharge: 'Dr. Leslie Lamport',
    totalStudents: 98,
    averageScore: 44.0,
    maxMarks: 50,
    isEndorsedByHOD: false,
  },
];

export const INITIAL_COURSES: CourseRecord[] = [
  {
    code: 'CS201',
    title: 'Data Structures & Algorithms',
    department: 'Computer Science & Engineering',
    semester: '3rd Semester B.Tech',
    credits: 4,
    studentsCount: 120,
    status: 'ACTIVE',
    assignedFacultyId: 'FAC_101',
    assignedFacultyName: 'Prof. Alan Turing',
    syllabusModules: [
      'Module 1: Linear Data Structures (Stacks, Queues, Linked Lists)',
      'Module 2: Non-Linear Structures (Binary Search Trees, AVL Trees)',
      'Module 3: Graph Algorithms (BFS, DFS, Dijkstra, Prim)',
      'Module 4: Hashing, Heaps and Priority Queues',
      'Module 5: Dynamic Programming and Greedy Design'
    ],
    outcomes: [
      { id: 'CO1', description: 'Analyze asymptotic computational complexity of algorithms using Big-O notation.', mappedPOs: ['PO1', 'PO2'] },
      { id: 'CO2', description: 'Implement non-linear data structures like balanced trees and priority heaps.', mappedPOs: ['PO1', 'PO3'] },
      { id: 'CO3', description: 'Design optimal graph traversal algorithms for complex network architectures.', mappedPOs: ['PO2', 'PO3', 'PO5'] },
      { id: 'CO4', description: 'Apply dynamic programming techniques to solve optimization problems.', mappedPOs: ['PO1', 'PO2', 'PO4'] },
      { id: 'CO5', description: 'Evaluate algorithmic efficiency tradeoffs in real-world memory constraints.', mappedPOs: ['PO3', 'PO12'] },
    ]
  },
  {
    code: 'CS301',
    title: 'Operating Systems & Kernel Design',
    department: 'Computer Science & Engineering',
    semester: '5th Semester B.Tech',
    credits: 4,
    studentsCount: 115,
    status: 'ACTIVE',
    assignedFacultyId: 'FAC_108',
    assignedFacultyName: 'Dr. Barbara Liskov',
    syllabusModules: [
      'Module 1: Kernel Architecture & System Calls',
      'Module 2: Process Scheduling & Thread Concurrency',
      'Module 3: Memory Virtualization & Paging',
      'Module 4: File Systems & Storage Devices',
      'Module 5: Security, Access Control & Protection'
    ],
    outcomes: [
      { id: 'CO1', description: 'Explain core OS abstractions including processes, threads, and memory virtualization.', mappedPOs: ['PO1', 'PO2'] },
      { id: 'CO2', description: 'Solve classical synchronization problems using semaphores, mutexes, and monitors.', mappedPOs: ['PO2', 'PO3'] },
      { id: 'CO3', description: 'Analyze multi-level paging schemes and page replacement policies.', mappedPOs: ['PO1', 'PO4'] },
      { id: 'CO4', description: 'Design journaling file systems resilient to unexpected crashes.', mappedPOs: ['PO3', 'PO5'] },
    ]
  },
  {
    code: 'CS302',
    title: 'Database Management Systems',
    department: 'Computer Science & Engineering',
    semester: '5th Semester B.Tech',
    credits: 3,
    studentsCount: 115,
    status: 'ACTIVE',
    assignedFacultyId: 'FAC_105',
    assignedFacultyName: 'Dr. Edgar Codd',
    syllabusModules: [
      'Module 1: Relational Algebra & ER Modeling',
      'Module 2: SQL, Complex Queries & Triggers',
      'Module 3: Normalization (1NF to BCNF)',
      'Module 4: Transaction Processing & ACID Properties',
      'Module 5: Indexing (B+ Trees) and Query Optimization'
    ],
    outcomes: [
      { id: 'CO1', description: 'Model real-world enterprise domains into formal Entity-Relationship blueprints.', mappedPOs: ['PO1', 'PO3'] },
      { id: 'CO2', description: 'Write optimized SQL queries including joins, window functions, and indexing.', mappedPOs: ['PO2', 'PO5'] },
      { id: 'CO3', description: 'Deconstruct relational tables to eliminate redundancy using BCNF.', mappedPOs: ['PO1', 'PO2'] },
      { id: 'CO4', description: 'Ensure concurrency control and recovery using two-phase locking protocols.', mappedPOs: ['PO3', 'PO4'] },
    ]
  }
];

export const INITIAL_FACULTY_MEMBERS: FacultyMember[] = [
  {
    id: 'FAC_101',
    name: 'Prof. Alan Turing',
    email: 'faculty@nexai.com',
    employeeId: 'EMP-CS-042',
    designation: 'Associate Professor',
    department: 'Computer Science & Engineering',
    assignedCourses: ['CS201'],
    tempPassword: 'password123',
    status: 'ACTIVE',
    createdDate: '2026-08-01',
  },
  {
    id: 'FAC_108',
    name: 'Dr. Barbara Liskov',
    email: 'b.liskov@univ.edu',
    employeeId: 'EMP-CS-088',
    designation: 'Professor',
    department: 'Computer Science & Engineering',
    assignedCourses: ['CS301'],
    tempPassword: 'password123',
    status: 'ACTIVE',
    createdDate: '2026-08-05',
  },
  {
    id: 'FAC_105',
    name: 'Dr. Edgar Codd',
    email: 'e.codd@univ.edu',
    employeeId: 'EMP-CS-055',
    designation: 'Assistant Professor',
    department: 'Computer Science & Engineering',
    assignedCourses: ['CS302'],
    tempPassword: 'password123',
    status: 'ACTIVE',
    createdDate: '2026-08-10',
  },
];

export const INITIAL_CIE_PAPERS: CIEQuestionPaper[] = [
  {
    id: 'CIE-CS201-TEST1',
    courseCode: 'CS201',
    courseTitle: 'Data Structures & Algorithms',
    semester: '3rd Sem B.Tech',
    testType: 'CIE-1',
    maxMarks: 30,
    facultyName: 'Prof. Alan Turing',
    facultyEmail: 'faculty@nexai.com',
    status: 'SUBMITTED_TO_HOD',
    submittedAt: '2026-09-02 11:30 AM',
    questions: [
      { id: 'q1', qNumber: '1a', text: 'Define Big-O notation and compute the tight bound for binary search recurrence T(n) = T(n/2) + O(1).', marks: 5, bloomsLevel: 'L2', co: 'CO1' },
      { id: 'q2', qNumber: '1b', text: 'Implement a circular queue using a fixed-size array and explain underflow/overflow handling.', marks: 10, bloomsLevel: 'L3', co: 'CO2' },
      { id: 'q3', qNumber: '2a', text: 'Given sequence [12, 11, 13, 5, 6, 7], construct a max-heap step-by-step and show the array representation.', marks: 8, bloomsLevel: 'L3', co: 'CO2' },
      { id: 'q4', qNumber: '2b', text: 'Differentiate between BFS and DFS traversal in terms of auxiliary memory requirements.', marks: 7, bloomsLevel: 'L4', co: 'CO3' },
    ]
  },
  {
    id: 'CIE-CS301-TEST1',
    courseCode: 'CS301',
    courseTitle: 'Operating Systems & Kernel Design',
    semester: '5th Sem B.Tech',
    testType: 'CIE-1',
    maxMarks: 30,
    facultyName: 'Dr. Barbara Liskov',
    facultyEmail: 'b.liskov@univ.edu',
    status: 'APPROVED',
    hodRemarks: 'Paper conforms with CO-PO mapping and Bloom taxonomy standards.',
    submittedAt: '2026-08-28 02:15 PM',
    questions: [
      { id: 'q10', qNumber: '1', text: 'Explain the dual-mode operation of CPU and how interrupts trigger trap into kernel mode.', marks: 10, bloomsLevel: 'L2', co: 'CO1' },
      { id: 'q11', qNumber: '2', text: 'Solve the Dining Philosophers synchronization problem using semaphores without deadlock.', marks: 12, bloomsLevel: 'L4', co: 'CO2' },
      { id: 'q12', qNumber: '3', text: 'Compare preemptive vs non-preemptive Shortest Job First scheduling.', marks: 8, bloomsLevel: 'L3', co: 'CO1' },
    ]
  }
];

export const INITIAL_DEPARTMENT_EXAM_SESSIONS: DepartmentExamSession[] = [
  {
    id: 'DEXAM-CS201-CIE1',
    title: 'CIE-1 Examination: Data Structures & Algorithms',
    examType: 'CIE-1',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    semester: '3rd Semester B.Tech',
    examDate: '2026-09-15',
    timeSlot: '09:30 AM - 11:00 AM (Morning)',
    roomsAllocated: ['Hall C-101', 'Hall C-102'],
    studentBatches: ['3rd Sem CSE-A (40)', '3rd Sem CSE-B (40)'],
    totalStudentsExpected: 80,
    paperSetterId: 'FAC_101',
    paperSetterName: 'Prof. Alan Turing',
    chiefInvigilatorId: 'FAC_108',
    chiefInvigilatorName: 'Dr. Barbara Liskov',
    evaluatorId: 'FAC_105',
    evaluatorName: 'Dr. Edgar Codd',
    evaluatorSessionKey: 'EVAL-FALL26-CS201-9042',
    status: 'FACULTY_APPOINTED',
  },
  {
    id: 'DEXAM-CS301-CIE1',
    title: 'CIE-1 Examination: Operating Systems & Kernel Design',
    examType: 'CIE-1',
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems & Kernel Design',
    semester: '5th Semester B.Tech',
    examDate: '2026-09-16',
    timeSlot: '02:00 PM - 03:30 PM (Afternoon)',
    roomsAllocated: ['Hall C-201', 'Hall C-202'],
    studentBatches: ['5th Sem CSE-A (38)', '5th Sem CSE-B (38)'],
    totalStudentsExpected: 76,
    paperSetterId: 'FAC_108',
    paperSetterName: 'Dr. Barbara Liskov',
    chiefInvigilatorId: 'FAC_105',
    chiefInvigilatorName: 'Dr. Edgar Codd',
    evaluatorId: 'FAC_101',
    evaluatorName: 'Prof. Alan Turing',
    evaluatorSessionKey: 'EVAL-FALL26-CS301-8192',
    status: 'QP_APPROVED',
  },
  {
    id: 'DEXAM-CS302-LAB1',
    title: 'Practical Lab Assessment: Database Systems & SQL',
    examType: 'LAB_INTERNAL',
    subjectCode: 'CS302',
    subjectTitle: 'Database Management Systems',
    semester: '5th Semester B.Tech',
    examDate: '2026-09-18',
    timeSlot: '09:30 AM - 12:30 PM (Batch 1)',
    roomsAllocated: ['Computing Lab 03', 'Computing Lab 04'],
    studentBatches: ['5th Sem CSE-A (38)'],
    totalStudentsExpected: 38,
    paperSetterId: 'FAC_105',
    paperSetterName: 'Dr. Edgar Codd',
    chiefInvigilatorId: 'FAC_101',
    chiefInvigilatorName: 'Prof. Alan Turing',
    evaluatorId: 'FAC_108',
    evaluatorName: 'Dr. Barbara Liskov',
    evaluatorSessionKey: 'EVAL-FALL26-CS302-3301',
    status: 'SCHEDULED',
  },
];

export const INITIAL_EXAM_HALLS: ExamHall[] = [
  {
    id: 'HALL-C101',
    roomNumber: 'Hall C-101',
    blockName: 'Aryabhata Academic Block - 1st Floor',
    rowsCount: 6,
    colsCount: 6,
    capacity: 36,
    benchType: 'SINGLE_SEATER',
    isCCTVEnabled: true,
    isAC: true,
    status: 'ACTIVE',
    lastAnnualAuditDate: '2026-07-15',
  },
  {
    id: 'HALL-C102',
    roomNumber: 'Hall C-102',
    blockName: 'Aryabhata Academic Block - 1st Floor',
    rowsCount: 6,
    colsCount: 6,
    capacity: 36,
    benchType: 'SINGLE_SEATER',
    isCCTVEnabled: true,
    isAC: true,
    status: 'ACTIVE',
    lastAnnualAuditDate: '2026-07-15',
  },
  {
    id: 'HALL-C201',
    roomNumber: 'Hall C-201',
    blockName: 'Aryabhata Academic Block - 2nd Floor',
    rowsCount: 6,
    colsCount: 6,
    capacity: 36,
    benchType: 'SINGLE_SEATER',
    isCCTVEnabled: true,
    isAC: false,
    status: 'ACTIVE',
    lastAnnualAuditDate: '2026-07-16',
  },
  {
    id: 'AUDI-1',
    roomNumber: 'Ramanujan Audi-1',
    blockName: 'Central Auditorium Complex - Ground Floor',
    rowsCount: 8,
    colsCount: 8,
    capacity: 64,
    benchType: 'SINGLE_SEATER',
    isCCTVEnabled: true,
    isAC: true,
    status: 'ACTIVE',
    lastAnnualAuditDate: '2026-07-20',
  },
  {
    id: 'COMP-LAB-03',
    roomNumber: 'Computing Lab 03',
    blockName: 'Alan Turing Computer Centre - 3rd Floor',
    rowsCount: 5,
    colsCount: 6,
    capacity: 30,
    benchType: 'SINGLE_SEATER',
    isCCTVEnabled: true,
    isAC: true,
    status: 'ACTIVE',
    lastAnnualAuditDate: '2026-07-18',
  },
];

export const INITIAL_ALLOCATED_SEATS: AllocatedSeat[] = [
  // Hall C-101 - Row A (Alternating 3rd Sem, 5th Sem, 7th Sem)
  { seatId: 'C101-A1', roomNumber: 'Hall C-101', rowLabel: 'A', colNumber: 1, seatNumber: 'A-01', studentUSN: '1RV23CS001', studentName: 'Aarav Sharma', semester: '3rd Sem', subjectCode: 'CS201', subjectTitle: 'Data Structures', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#3B82F6' },
  { seatId: 'C101-A2', roomNumber: 'Hall C-101', rowLabel: 'A', colNumber: 2, seatNumber: 'A-02', studentUSN: '1RV22CS014', studentName: 'Divya Rao', semester: '5th Sem', subjectCode: 'CS301', subjectTitle: 'Operating Systems', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#10B981' },
  { seatId: 'C101-A3', roomNumber: 'Hall C-101', rowLabel: 'A', colNumber: 3, seatNumber: 'A-03', studentUSN: '1RV21CS008', studentName: 'Rahul Varma', semester: '7th Sem', subjectCode: 'CS401', subjectTitle: 'Cloud Computing', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#8B5CF6' },
  { seatId: 'C101-A4', roomNumber: 'Hall C-101', rowLabel: 'A', colNumber: 4, seatNumber: 'A-04', studentUSN: '1RV23CS002', studentName: 'Ananya Verma', semester: '3rd Sem', subjectCode: 'CS201', subjectTitle: 'Data Structures', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#3B82F6' },
  { seatId: 'C101-A5', roomNumber: 'Hall C-101', rowLabel: 'A', colNumber: 5, seatNumber: 'A-05', studentUSN: '1RV22CS029', studentName: 'Karthik S', semester: '5th Sem', subjectCode: 'CS301', subjectTitle: 'Operating Systems', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#10B981' },
  { seatId: 'C101-A6', roomNumber: 'Hall C-101', rowLabel: 'A', colNumber: 6, seatNumber: 'A-06', studentUSN: '1RV21CS019', studentName: 'Sneha Patil', semester: '7th Sem', subjectCode: 'CS401', subjectTitle: 'Cloud Computing', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#8B5CF6' },

  // Hall C-101 - Row B (Shifted to ensure diagonal anti-cheating separation)
  { seatId: 'C101-B1', roomNumber: 'Hall C-101', rowLabel: 'B', colNumber: 1, seatNumber: 'B-01', studentUSN: '1RV22CS032', studentName: 'Manoj Kumar', semester: '5th Sem', subjectCode: 'CS301', subjectTitle: 'Operating Systems', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#10B981' },
  { seatId: 'C101-B2', roomNumber: 'Hall C-101', rowLabel: 'B', colNumber: 2, seatNumber: 'B-02', studentUSN: '1RV21CS035', studentName: 'Vikram Hegde', semester: '7th Sem', subjectCode: 'CS401', subjectTitle: 'Cloud Computing', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#8B5CF6' },
  { seatId: 'C101-B3', roomNumber: 'Hall C-101', rowLabel: 'B', colNumber: 3, seatNumber: 'B-03', studentUSN: '1RV23CS003', studentName: 'Rohan Mehta', semester: '3rd Sem', subjectCode: 'CS201', subjectTitle: 'Data Structures', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#3B82F6' },
  { seatId: 'C101-B4', roomNumber: 'Hall C-101', rowLabel: 'B', colNumber: 4, seatNumber: 'B-04', studentUSN: '1RV22CS045', studentName: 'Pooja Bhat', semester: '5th Sem', subjectCode: 'CS301', subjectTitle: 'Operating Systems', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#10B981' },
  { seatId: 'C101-B5', roomNumber: 'Hall C-101', rowLabel: 'B', colNumber: 5, seatNumber: 'B-05', studentUSN: '1RV21CS042', studentName: 'Deepa Nair', semester: '7th Sem', subjectCode: 'CS401', subjectTitle: 'Cloud Computing', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#8B5CF6' },
  { seatId: 'C101-B6', roomNumber: 'Hall C-101', rowLabel: 'B', colNumber: 6, seatNumber: 'B-06', studentUSN: '1RV23CS004', studentName: 'Priya Nair', semester: '3rd Sem', subjectCode: 'CS201', subjectTitle: 'Data Structures', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#3B82F6' },

  // Hall C-101 - Row C
  { seatId: 'C101-C1', roomNumber: 'Hall C-101', rowLabel: 'C', colNumber: 1, seatNumber: 'C-01', studentUSN: '1RV21CS048', studentName: 'Aditya K', semester: '7th Sem', subjectCode: 'CS401', subjectTitle: 'Cloud Computing', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#8B5CF6' },
  { seatId: 'C101-C2', roomNumber: 'Hall C-101', rowLabel: 'C', colNumber: 2, seatNumber: 'C-02', studentUSN: '1RV23CS005', studentName: 'Tanvi Shah', semester: '3rd Sem', subjectCode: 'CS201', subjectTitle: 'Data Structures', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#3B82F6' },
  { seatId: 'C101-C3', roomNumber: 'Hall C-101', rowLabel: 'C', colNumber: 3, seatNumber: 'C-03', studentUSN: '1RV22CS051', studentName: 'Sanjay Deshmukh', semester: '5th Sem', subjectCode: 'CS301', subjectTitle: 'Operating Systems', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#10B981' },
  { seatId: 'C101-C4', roomNumber: 'Hall C-101', rowLabel: 'C', colNumber: 4, seatNumber: 'C-04', studentUSN: '1RV21CS054', studentName: 'Neha Sen', semester: '7th Sem', subjectCode: 'CS401', subjectTitle: 'Cloud Computing', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#8B5CF6' },
  { seatId: 'C101-C5', roomNumber: 'Hall C-101', rowLabel: 'C', colNumber: 5, seatNumber: 'C-05', studentUSN: '1RV23CS006', studentName: 'Adarsh K', semester: '3rd Sem', subjectCode: 'CS201', subjectTitle: 'Data Structures', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#3B82F6' },
  { seatId: 'C101-C6', roomNumber: 'Hall C-101', rowLabel: 'C', colNumber: 6, seatNumber: 'C-06', studentUSN: '1RV22CS060', studentName: 'Shreya Roy', semester: '5th Sem', subjectCode: 'CS301', subjectTitle: 'Operating Systems', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#10B981' },

  // Hall C-102 - Row A
  { seatId: 'C102-A1', roomNumber: 'Hall C-102', rowLabel: 'A', colNumber: 1, seatNumber: 'A-01', studentUSN: '1RV23CS007', studentName: 'Siddharth Joshi', semester: '3rd Sem', subjectCode: 'CS201', subjectTitle: 'Data Structures', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#3B82F6' },
  { seatId: 'C102-A2', roomNumber: 'Hall C-102', rowLabel: 'A', colNumber: 2, seatNumber: 'A-02', studentUSN: '1RV22CS065', studentName: 'Varun Reddy', semester: '5th Sem', subjectCode: 'CS301', subjectTitle: 'Operating Systems', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#10B981' },
  { seatId: 'C102-A3', roomNumber: 'Hall C-102', rowLabel: 'A', colNumber: 3, seatNumber: 'A-03', studentUSN: '1RV21CS060', studentName: 'Meenakshi Iyer', semester: '7th Sem', subjectCode: 'CS401', subjectTitle: 'Cloud Computing', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#8B5CF6' },
  { seatId: 'C102-A4', roomNumber: 'Hall C-102', rowLabel: 'A', colNumber: 4, seatNumber: 'A-04', studentUSN: '1RV23CS008', studentName: 'Meera Sen', semester: '3rd Sem', subjectCode: 'CS201', subjectTitle: 'Data Structures', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#3B82F6' },
  { seatId: 'C102-A5', roomNumber: 'Hall C-102', rowLabel: 'A', colNumber: 5, seatNumber: 'A-05', studentUSN: '1RV22CS070', studentName: 'Harish Babu', semester: '5th Sem', subjectCode: 'CS301', subjectTitle: 'Operating Systems', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#10B981' },
  { seatId: 'C102-A6', roomNumber: 'Hall C-102', rowLabel: 'A', colNumber: 6, seatNumber: 'A-06', studentUSN: '1RV21CS065', studentName: 'Lavanya S', semester: '7th Sem', subjectCode: 'CS401', subjectTitle: 'Cloud Computing', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM', colorTheme: '#8B5CF6' },
];

export const INITIAL_FACULTY_DUTY_ALLOCATIONS: FacultyDutyAllocation[] = [
  {
    id: 'FDA_101',
    facultyId: 'FAC_101',
    facultyName: 'Prof. Alan Turing',
    employeeId: 'EMP-CS-101',
    dutyCount: 2,
    assignments: [
      { roomNumber: 'Hall C-101', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM (Slot 1)', role: 'CHIEF_INVIGILATOR' },
      { roomNumber: 'Computing Lab 03', examDate: '2026-09-18', timeSlot: '09:30 AM - 12:30 PM (Slot 1)', role: 'CHIEF_INVIGILATOR' },
    ],
  },
  {
    id: 'FDA_105',
    facultyId: 'FAC_105',
    facultyName: 'Dr. Edgar Codd',
    employeeId: 'EMP-CS-105',
    dutyCount: 2,
    assignments: [
      { roomNumber: 'Hall C-102', examDate: '2026-09-15', timeSlot: '09:30 AM - 11:00 AM (Slot 1)', role: 'CHIEF_INVIGILATOR' },
      { roomNumber: 'Hall C-201', examDate: '2026-09-16', timeSlot: '02:00 PM - 03:30 PM (Slot 2)', role: 'CHIEF_INVIGILATOR' },
    ],
  },
  {
    id: 'FDA_108',
    facultyId: 'FAC_108',
    facultyName: 'Dr. Barbara Liskov',
    employeeId: 'EMP-CS-108',
    dutyCount: 2,
    assignments: [
      { roomNumber: 'Hall C-101', examDate: '2026-09-16', timeSlot: '02:00 PM - 03:30 PM (Slot 2)', role: 'CHIEF_INVIGILATOR' },
      { roomNumber: 'Ramanujan Audi-1', examDate: '2026-09-17', timeSlot: '09:30 AM - 11:00 AM (Slot 1)', role: 'CHIEF_INVIGILATOR' },
    ],
  },
];



