import { StudentEligibilityRecord, HallTicketRecord, FacultyNomination, CIEMarksSheet } from './types';

export const INITIAL_STUDENTS: StudentEligibilityRecord[] = [
  {
    id: 'std_1',
    usn: '1RV23CS001',
    name: 'Aarav Sharma',
    email: 'aarav.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    attendancePercent: 92.5,
    totalClassesHeld: 80,
    classesAttended: 74,
    cieMarksAvg: 44.5,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
    hallTicketNumber: 'HT-FALL26-CS-001',
  },
  {
    id: 'std_2',
    usn: '1RV23CS002',
    name: 'Ananya Deshmukh',
    email: 'ananya.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    attendancePercent: 88.0,
    totalClassesHeld: 80,
    classesAttended: 70,
    cieMarksAvg: 46.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
    hallTicketNumber: 'HT-FALL26-CS-002',
  },
  {
    id: 'std_3',
    usn: '1RV23CS003',
    name: 'Rohan Verma',
    email: 'rohan.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    attendancePercent: 68.5,
    totalClassesHeld: 80,
    classesAttended: 55,
    cieMarksAvg: 38.0,
    status: 'CONDONABLE',
    hasFeeDues: false,
    condonationReason: 'Represented University in Inter-Collegiate ACM-ICPC Coding Regional Finals (Medical & Attendance waiver requested).',
    condonationApproved: false,
    hallTicketIssued: false,
  },
  {
    id: 'std_4',
    usn: '1RV23CS004',
    name: 'Pooja Hegde',
    email: 'pooja.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    attendancePercent: 54.0,
    totalClassesHeld: 80,
    classesAttended: 43,
    cieMarksAvg: 22.0,
    status: 'DETAINED',
    hasFeeDues: false,
    hallTicketIssued: false,
  },
  {
    id: 'std_5',
    usn: '1RV23CS005',
    name: 'Vikramaditya Rao',
    email: 'vikram.cs23@rvce.edu.in',
    semester: '3rd Sem',
    department: 'Computer Science',
    section: 'A',
    attendancePercent: 82.0,
    totalClassesHeld: 80,
    classesAttended: 66,
    cieMarksAvg: 41.0,
    status: 'FEE_BLOCKED',
    hasFeeDues: true,
    dueAmount: '₹18,500 ($220 USD)',
    hallTicketIssued: false,
  },
  {
    id: 'std_6',
    usn: '1RV22CS045',
    name: 'Diya Nambiar',
    email: 'diya.cs22@rvce.edu.in',
    semester: '5th Sem',
    department: 'Computer Science',
    section: 'B',
    attendancePercent: 95.0,
    totalClassesHeld: 76,
    classesAttended: 72,
    cieMarksAvg: 48.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
    hallTicketNumber: 'HT-FALL26-CS-045',
  },
  {
    id: 'std_7',
    usn: '1RV22CS048',
    name: 'Kabir Mehta',
    email: 'kabir.cs22@rvce.edu.in',
    semester: '5th Sem',
    department: 'Computer Science',
    section: 'B',
    attendancePercent: 71.0,
    totalClassesHeld: 76,
    classesAttended: 54,
    cieMarksAvg: 35.5,
    status: 'CONDONABLE',
    hasFeeDues: false,
    condonationReason: 'Hospitalization for Dengue Fever (Medical Certificate verified by University Health Officer).',
    condonationApproved: true,
    hallTicketIssued: true,
    hallTicketNumber: 'HT-FALL26-CS-048',
  },
  {
    id: 'std_8',
    usn: '1RV21CS089',
    name: 'Siddharth Pillai',
    email: 'siddharth.cs21@rvce.edu.in',
    semester: '7th Sem',
    department: 'Computer Science',
    section: 'A',
    attendancePercent: 86.5,
    totalClassesHeld: 70,
    classesAttended: 61,
    cieMarksAvg: 45.0,
    status: 'ELIGIBLE',
    hasFeeDues: false,
    hallTicketIssued: true,
    hallTicketNumber: 'HT-FALL26-CS-089',
  },
];

export const INITIAL_HALL_TICKETS: HallTicketRecord[] = [
  {
    id: 'ht_1',
    ticketNumber: 'HT-FALL26-CS-001',
    usn: '1RV23CS001',
    studentName: 'Aarav Sharma',
    semester: '3rd Semester B.Tech',
    department: 'Department of Computer Science & Engineering',
    examSession: 'Fall End-Semester Examinations 2026',
    generatedAt: '2026-08-30 11:30 IST',
    isRevoked: false,
    qrPayload: 'NEXAI_ADMIT_VERIFIED_1RV23CS001_HT-FALL26-CS-001_SIGN_HOD_CSE_OK',
    slots: [
      { subjectCode: 'CS201', subjectTitle: 'Data Structures & Algorithms', examDate: 'Oct 15, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-01' },
      { subjectCode: 'MA201', subjectTitle: 'Discrete Mathematical Structures', examDate: 'Oct 18, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-01' },
      { subjectCode: 'CS202', subjectTitle: 'Digital Logic & Microprocessors', examDate: 'Oct 21, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-102', deskNumber: 'D-14' },
      { subjectCode: 'EC205', subjectTitle: 'Analog Electronics Circuits', examDate: 'Oct 24, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-01' },
    ],
  },
  {
    id: 'ht_2',
    ticketNumber: 'HT-FALL26-CS-002',
    usn: '1RV23CS002',
    studentName: 'Ananya Deshmukh',
    semester: '3rd Semester B.Tech',
    department: 'Department of Computer Science & Engineering',
    examSession: 'Fall End-Semester Examinations 2026',
    generatedAt: '2026-08-30 11:30 IST',
    isRevoked: false,
    qrPayload: 'NEXAI_ADMIT_VERIFIED_1RV23CS002_HT-FALL26-CS-002_SIGN_HOD_CSE_OK',
    slots: [
      { subjectCode: 'CS201', subjectTitle: 'Data Structures & Algorithms', examDate: 'Oct 15, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-02' },
      { subjectCode: 'MA201', subjectTitle: 'Discrete Mathematical Structures', examDate: 'Oct 18, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-02' },
      { subjectCode: 'CS202', subjectTitle: 'Digital Logic & Microprocessors', examDate: 'Oct 21, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-102', deskNumber: 'D-15' },
      { subjectCode: 'EC205', subjectTitle: 'Analog Electronics Circuits', examDate: 'Oct 24, 2026', examTime: '10:00 AM - 01:00 PM', roomAllocated: 'Hall A-101', deskNumber: 'D-02' },
    ],
  },
  {
    id: 'ht_3',
    ticketNumber: 'HT-FALL26-CS-045',
    usn: '1RV22CS045',
    studentName: 'Diya Nambiar',
    semester: '5th Semester B.Tech',
    department: 'Department of Computer Science & Engineering',
    examSession: 'Fall End-Semester Examinations 2026',
    generatedAt: '2026-08-30 12:15 IST',
    isRevoked: false,
    qrPayload: 'NEXAI_ADMIT_VERIFIED_1RV22CS045_HT-FALL26-CS-045_SIGN_HOD_CSE_OK',
    slots: [
      { subjectCode: 'CS301', subjectTitle: 'Operating Systems', examDate: 'Oct 16, 2026', examTime: '02:00 PM - 05:00 PM', roomAllocated: 'Hall B-201', deskNumber: 'D-10' },
      { subjectCode: 'CS302', subjectTitle: 'Database Management Systems', examDate: 'Oct 19, 2026', examTime: '02:00 PM - 05:00 PM', roomAllocated: 'Hall B-201', deskNumber: 'D-10' },
      { subjectCode: 'CS303', subjectTitle: 'Computer Networks', examDate: 'Oct 22, 2026', examTime: '02:00 PM - 05:00 PM', roomAllocated: 'Hall B-202', deskNumber: 'D-05' },
    ],
  },
];

export const INITIAL_FACULTY_NOMINATIONS: FacultyNomination[] = [
  {
    id: 'fn_1',
    facultyId: 'FAC_104',
    name: 'Dr. Alan Turing',
    designation: 'Professor & Head of Computing',
    email: 'alan.turing@univ.edu',
    phone: '+91 98450 12345',
    experienceYears: 18,
    assignedRole: 'SETTER',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    status: 'ACCEPTED',
  },
  {
    id: 'fn_2',
    facultyId: 'FAC_108',
    name: 'Dr. Barbara Liskov',
    designation: 'Associate Professor',
    email: 'b.liskov@univ.edu',
    phone: '+91 98450 23456',
    experienceYears: 12,
    assignedRole: 'SETTER',
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems',
    status: 'ACCEPTED',
  },
  {
    id: 'fn_3',
    facultyId: 'FAC_112',
    name: 'Prof. Donald Knuth',
    designation: 'Visiting Emeritus Professor',
    email: 'd.knuth@univ.edu',
    phone: '+91 98450 34567',
    experienceYears: 25,
    assignedRole: 'EVALUATOR',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    status: 'NOMINATED',
  },
  {
    id: 'fn_4',
    facultyId: 'FAC_119',
    name: 'Dr. Edsger Dijkstra',
    designation: 'Professor of Algorithms',
    email: 'e.dijkstra@univ.edu',
    phone: '+91 98450 45678',
    experienceYears: 20,
    assignedRole: 'CHIEF_INVIGILATOR',
    subjectCode: 'EXAM_FALL2026',
    subjectTitle: 'Main Examination Block A',
    status: 'ACCEPTED',
  },
];

export const INITIAL_CIE_SHEETS: CIEMarksSheet[] = [
  {
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    semester: '3rd Semester B.Tech',
    facultyInCharge: 'Dr. Alan Turing',
    totalStudents: 120,
    averageScore: 41.2,
    maxMarks: 50,
    isEndorsedByHOD: true,
    endorsedAt: '2026-08-29 16:30 IST',
  },
  {
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems',
    semester: '5th Semester B.Tech',
    facultyInCharge: 'Dr. Barbara Liskov',
    totalStudents: 115,
    averageScore: 43.8,
    maxMarks: 50,
    isEndorsedByHOD: true,
    endorsedAt: '2026-08-30 14:15 IST',
  },
  {
    subjectCode: 'CS302',
    subjectTitle: 'Database Management Systems',
    semester: '5th Semester B.Tech',
    facultyInCharge: 'Dr. Codd',
    totalStudents: 115,
    averageScore: 39.5,
    maxMarks: 50,
    isEndorsedByHOD: false,
  },
  {
    subjectCode: 'CS401',
    subjectTitle: 'Distributed Systems & Cloud Computing',
    semester: '7th Semester B.Tech',
    facultyInCharge: 'Dr. Leslie Lamport',
    totalStudents: 98,
    averageScore: 44.0,
    maxMarks: 50,
    isEndorsedByHOD: false,
  },
];
