import {
  AssignedCourse,
  StudentGradeRecord,
  FacultyCIEPaper,
  DailyAttendanceRecord,
  CIEScannedScript
} from './types';

export const INITIAL_ASSIGNED_COURSES: AssignedCourse[] = [
  {
    code: 'CS201',
    title: 'Data Structures & Algorithms',
    department: 'Computer Science & Engineering',
    semester: '3rd Semester B.Tech (Sec A)',
    credits: 4,
    totalEnrolled: 40,
    avgAttendance: 84.5,
    syllabusCompletion: 68,
    nextClassTime: 'Today, 10:30 AM (LH-201)',
    cie1Status: 'APPROVED',
  },
  {
    code: 'CS303',
    title: 'Computer Networks & Protocols',
    department: 'Computer Science & Engineering',
    semester: '5th Semester B.Tech (Sec B)',
    credits: 4,
    totalEnrolled: 36,
    avgAttendance: 79.2,
    syllabusCompletion: 52,
    nextClassTime: 'Tomorrow, 02:00 PM (LH-104)',
    cie1Status: 'DRAFT',
  },
];

export const INITIAL_DAILY_ATTENDANCE_LOGS: DailyAttendanceRecord[] = [
  {
    id: 'att-log-01',
    courseCode: 'CS201',
    date: '2026-09-02',
    sessionNumber: 39,
    sessionTopic: 'Binary Search Trees & Node Deletion Cases',
    totalStudents: 40,
    presentCount: 38,
    absentCount: 2,
    absentUSNs: ['1MS24CS004', '1MS24CS007'],
    recordedAt: '2026-09-02 11:20 AM',
  },
  {
    id: 'att-log-02',
    courseCode: 'CS201',
    date: '2026-08-31',
    sessionNumber: 38,
    sessionTopic: 'Binary Tree Traversals (Inorder, Preorder, Postorder)',
    totalStudents: 40,
    presentCount: 39,
    absentCount: 1,
    absentUSNs: ['1MS24CS004'],
    recordedAt: '2026-08-31 11:22 AM',
  },
  {
    id: 'att-log-03',
    courseCode: 'CS303',
    date: '2026-09-01',
    sessionNumber: 26,
    sessionTopic: 'TCP Sliding Window Protocol & Congestion Control',
    totalStudents: 36,
    presentCount: 33,
    absentCount: 3,
    absentUSNs: ['1MS23CS002', '1MS23CS005', '1MS23CS008'],
    recordedAt: '2026-09-01 03:00 PM',
  },
];

export const INITIAL_CIE_SCANNED_SCRIPTS: CIEScannedScript[] = [
  {
    id: 'cie_script_001',
    studentId: 's1',
    studentUSN: '1MS24CS001',
    studentName: 'Aarav Sharma',
    courseCode: 'CS201',
    courseTitle: 'Data Structures & Algorithms',
    testType: 'CIE-1',
    submittedAt: '2026-09-01 12:00 PM',
    totalPages: 4,
    status: 'EVALUATED',
    maxMarks: 30,
    evaluatorTotalMarks: 27,
    aiSuggestedMarks: 26,
    evaluatedAt: '2026-09-02 04:15 PM',
    generalFeedback: 'Exceptional clarity in recurrence relations and AVL tree rotations. Neat diagrammatic representation.',
    annotations: [
      { id: 'ann_01', pageNumber: 1, type: 'TICK', x: 78, y: 22 },
      { id: 'ann_02', pageNumber: 1, type: 'STEP_MARK', x: 86, y: 44, marksValue: 5 },
      { id: 'ann_03', pageNumber: 2, type: 'TICK', x: 80, y: 35 },
    ],
    questions: [
      {
        id: 'q1',
        questionNumber: '1a',
        questionText: 'Define Big-O notation and compute tight bound for binary search recurrence T(n) = T(n/2) + O(1).',
        maxMarks: 5,
        bloomsLevel: 'L2',
        co: 'CO1',
        aiSuggestedMarks: 5,
        awardedMarks: 5,
        evaluatorRemarks: 'Exact Master Theorem case applied correctly.',
        isEvaluated: true,
      },
      {
        id: 'q2',
        questionNumber: '1b',
        questionText: 'Implement a circular queue using a fixed-size array and explain underflow/overflow handling.',
        maxMarks: 10,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 9,
        awardedMarks: 9,
        evaluatorRemarks: 'Full modulo arithmetic logic implemented cleanly.',
        isEvaluated: true,
      },
      {
        id: 'q3',
        questionNumber: '2a',
        questionText: 'Given sequence [12, 11, 13, 5, 6, 7], construct a max-heap step-by-step and show the array representation.',
        maxMarks: 8,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 7,
        awardedMarks: 7,
        evaluatorRemarks: 'Correct heapify steps. Minor indentation gap.',
        isEvaluated: true,
      },
      {
        id: 'q4',
        questionNumber: '2b',
        questionText: 'Differentiate between BFS and DFS traversal in terms of auxiliary memory requirements.',
        maxMarks: 7,
        bloomsLevel: 'L4',
        co: 'CO3',
        aiSuggestedMarks: 6,
        awardedMarks: 6,
        evaluatorRemarks: 'Good queue vs call stack space comparison.',
        isEvaluated: true,
      },
    ],
  },
  {
    id: 'cie_script_002',
    studentId: 's2',
    studentUSN: '1MS24CS002',
    studentName: 'Diya Patel',
    courseCode: 'CS201',
    courseTitle: 'Data Structures & Algorithms',
    testType: 'CIE-1',
    submittedAt: '2026-09-01 12:05 PM',
    totalPages: 4,
    status: 'PENDING_VALUATION',
    maxMarks: 30,
    aiSuggestedMarks: 24,
    annotations: [],
    questions: [
      {
        id: 'q1',
        questionNumber: '1a',
        questionText: 'Define Big-O notation and compute tight bound for binary search recurrence T(n) = T(n/2) + O(1).',
        maxMarks: 5,
        bloomsLevel: 'L2',
        co: 'CO1',
        aiSuggestedMarks: 4,
        awardedMarks: 4,
        evaluatorRemarks: '',
        isEvaluated: false,
      },
      {
        id: 'q2',
        questionNumber: '1b',
        questionText: 'Implement a circular queue using a fixed-size array and explain underflow/overflow handling.',
        maxMarks: 10,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 8,
        awardedMarks: 8,
        evaluatorRemarks: '',
        isEvaluated: false,
      },
      {
        id: 'q3',
        questionNumber: '2a',
        questionText: 'Given sequence [12, 11, 13, 5, 6, 7], construct a max-heap step-by-step and show the array representation.',
        maxMarks: 8,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 7,
        awardedMarks: 7,
        evaluatorRemarks: '',
        isEvaluated: false,
      },
      {
        id: 'q4',
        questionNumber: '2b',
        questionText: 'Differentiate between BFS and DFS traversal in terms of auxiliary memory requirements.',
        maxMarks: 7,
        bloomsLevel: 'L4',
        co: 'CO3',
        aiSuggestedMarks: 5,
        awardedMarks: 5,
        evaluatorRemarks: '',
        isEvaluated: false,
      },
    ],
  },
  {
    id: 'cie_script_003',
    studentId: 's3',
    studentUSN: '1MS24CS003',
    studentName: 'Rohan Verma',
    courseCode: 'CS201',
    courseTitle: 'Data Structures & Algorithms',
    testType: 'CIE-1',
    submittedAt: '2026-09-01 12:02 PM',
    totalPages: 3,
    status: 'PENDING_VALUATION',
    maxMarks: 30,
    aiSuggestedMarks: 21,
    annotations: [],
    questions: [
      {
        id: 'q1',
        questionNumber: '1a',
        questionText: 'Define Big-O notation and compute tight bound for binary search recurrence T(n) = T(n/2) + O(1).',
        maxMarks: 5,
        bloomsLevel: 'L2',
        co: 'CO1',
        aiSuggestedMarks: 4,
        awardedMarks: 4,
        isEvaluated: false,
      },
      {
        id: 'q2',
        questionNumber: '1b',
        questionText: 'Implement a circular queue using a fixed-size array and explain underflow/overflow handling.',
        maxMarks: 10,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 7,
        awardedMarks: 7,
        isEvaluated: false,
      },
      {
        id: 'q3',
        questionNumber: '2a',
        questionText: 'Given sequence [12, 11, 13, 5, 6, 7], construct a max-heap step-by-step and show the array representation.',
        maxMarks: 8,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 6,
        awardedMarks: 6,
        isEvaluated: false,
      },
      {
        id: 'q4',
        questionNumber: '2b',
        questionText: 'Differentiate between BFS and DFS traversal in terms of auxiliary memory requirements.',
        maxMarks: 7,
        bloomsLevel: 'L4',
        co: 'CO3',
        aiSuggestedMarks: 4,
        awardedMarks: 4,
        isEvaluated: false,
      },
    ],
  },
  {
    id: 'cie_script_004',
    studentId: 's4',
    studentUSN: '1MS24CS004',
    studentName: 'Ananya Reddy',
    courseCode: 'CS201',
    courseTitle: 'Data Structures & Algorithms',
    testType: 'CIE-1',
    submittedAt: '2026-09-01 12:10 PM',
    totalPages: 3,
    status: 'PENDING_VALUATION',
    maxMarks: 30,
    aiSuggestedMarks: 18,
    annotations: [],
    questions: [
      {
        id: 'q1',
        questionNumber: '1a',
        questionText: 'Define Big-O notation and compute tight bound for binary search recurrence T(n) = T(n/2) + O(1).',
        maxMarks: 5,
        bloomsLevel: 'L2',
        co: 'CO1',
        aiSuggestedMarks: 3,
        awardedMarks: 3,
        isEvaluated: false,
      },
      {
        id: 'q2',
        questionNumber: '1b',
        questionText: 'Implement a circular queue using a fixed-size array and explain underflow/overflow handling.',
        maxMarks: 10,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 6,
        awardedMarks: 6,
        isEvaluated: false,
      },
      {
        id: 'q3',
        questionNumber: '2a',
        questionText: 'Given sequence [12, 11, 13, 5, 6, 7], construct a max-heap step-by-step and show the array representation.',
        maxMarks: 8,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 5,
        awardedMarks: 5,
        isEvaluated: false,
      },
      {
        id: 'q4',
        questionNumber: '2b',
        questionText: 'Differentiate between BFS and DFS traversal in terms of auxiliary memory requirements.',
        maxMarks: 7,
        bloomsLevel: 'L4',
        co: 'CO3',
        aiSuggestedMarks: 4,
        awardedMarks: 4,
        isEvaluated: false,
      },
    ],
  },
  {
    id: 'cie_script_005',
    studentId: 's5',
    studentUSN: '1MS24CS005',
    studentName: 'Vikram Singh',
    courseCode: 'CS201',
    courseTitle: 'Data Structures & Algorithms',
    testType: 'CIE-1',
    submittedAt: '2026-09-01 12:01 PM',
    totalPages: 4,
    status: 'EVALUATED',
    maxMarks: 30,
    evaluatorTotalMarks: 25,
    aiSuggestedMarks: 25,
    evaluatedAt: '2026-09-02 04:30 PM',
    generalFeedback: 'Well structured implementation of circular queue with good boundary test cases.',
    annotations: [],
    questions: [
      {
        id: 'q1',
        questionNumber: '1a',
        questionText: 'Define Big-O notation and compute tight bound for binary search recurrence T(n) = T(n/2) + O(1).',
        maxMarks: 5,
        bloomsLevel: 'L2',
        co: 'CO1',
        aiSuggestedMarks: 5,
        awardedMarks: 5,
        isEvaluated: true,
      },
      {
        id: 'q2',
        questionNumber: '1b',
        questionText: 'Implement a circular queue using a fixed-size array and explain underflow/overflow handling.',
        maxMarks: 10,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 8,
        awardedMarks: 8,
        isEvaluated: true,
      },
      {
        id: 'q3',
        questionNumber: '2a',
        questionText: 'Given sequence [12, 11, 13, 5, 6, 7], construct a max-heap step-by-step and show the array representation.',
        maxMarks: 8,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 6,
        awardedMarks: 6,
        isEvaluated: true,
      },
      {
        id: 'q4',
        questionNumber: '2b',
        questionText: 'Differentiate between BFS and DFS traversal in terms of auxiliary memory requirements.',
        maxMarks: 7,
        bloomsLevel: 'L4',
        co: 'CO3',
        aiSuggestedMarks: 6,
        awardedMarks: 6,
        isEvaluated: true,
      },
    ],
  },
  {
    id: 'cie_script_006',
    studentId: 's6',
    studentUSN: '1MS24CS006',
    studentName: 'Priya Nair',
    courseCode: 'CS201',
    courseTitle: 'Data Structures & Algorithms',
    testType: 'CIE-1',
    submittedAt: '2026-09-01 12:04 PM',
    totalPages: 4,
    status: 'PENDING_VALUATION',
    maxMarks: 30,
    aiSuggestedMarks: 28,
    annotations: [],
    questions: [
      {
        id: 'q1',
        questionNumber: '1a',
        questionText: 'Define Big-O notation and compute tight bound for binary search recurrence T(n) = T(n/2) + O(1).',
        maxMarks: 5,
        bloomsLevel: 'L2',
        co: 'CO1',
        aiSuggestedMarks: 5,
        awardedMarks: 5,
        isEvaluated: false,
      },
      {
        id: 'q2',
        questionNumber: '1b',
        questionText: 'Implement a circular queue using a fixed-size array and explain underflow/overflow handling.',
        maxMarks: 10,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 9,
        awardedMarks: 9,
        isEvaluated: false,
      },
      {
        id: 'q3',
        questionNumber: '2a',
        questionText: 'Given sequence [12, 11, 13, 5, 6, 7], construct a max-heap step-by-step and show the array representation.',
        maxMarks: 8,
        bloomsLevel: 'L3',
        co: 'CO2',
        aiSuggestedMarks: 7,
        awardedMarks: 7,
        isEvaluated: false,
      },
      {
        id: 'q4',
        questionNumber: '2b',
        questionText: 'Differentiate between BFS and DFS traversal in terms of auxiliary memory requirements.',
        maxMarks: 7,
        bloomsLevel: 'L4',
        co: 'CO3',
        aiSuggestedMarks: 7,
        awardedMarks: 7,
        isEvaluated: false,
      },
    ],
  }
];

export const INITIAL_STUDENT_ROSTER: StudentGradeRecord[] = [
  {
    id: 's1',
    usn: '1MS24CS001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@univ.edu',
    courseCode: 'CS201',
    attendancePercent: 88,
    classesHeld: 40,
    classesAttended: 35,
    cie1: 27,
    cie2: 26,
    labOrQuiz: 18,
    totalCIE: 45,
  },
  {
    id: 's2',
    usn: '1MS24CS002',
    name: 'Diya Patel',
    email: 'diya.patel@univ.edu',
    courseCode: 'CS201',
    attendancePercent: 92,
    classesHeld: 40,
    classesAttended: 37,
    cie1: 29,
    cie2: 28,
    labOrQuiz: 19,
    totalCIE: 48,
  },
  {
    id: 's3',
    usn: '1MS24CS003',
    name: 'Rohan Verma',
    email: 'rohan.verma@univ.edu',
    courseCode: 'CS201',
    attendancePercent: 71, // Below 75% cutoff!
    classesHeld: 40,
    classesAttended: 28,
    cie1: 18,
    cie2: 20,
    labOrQuiz: 14,
    totalCIE: 33,
    remarks: 'Medical leave certificate pending verification with HOD',
  },
  {
    id: 's4',
    usn: '1MS24CS004',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@univ.edu',
    courseCode: 'CS201',
    attendancePercent: 95,
    classesHeld: 40,
    classesAttended: 38,
    cie1: 30,
    cie2: 29,
    labOrQuiz: 20,
    totalCIE: 50,
  },
  {
    id: 's5',
    usn: '1MS24CS005',
    name: 'Vikramaditya Nair',
    email: 'vikram.nair@univ.edu',
    courseCode: 'CS201',
    attendancePercent: 68, // Below 75% cutoff!
    classesHeld: 40,
    classesAttended: 27,
    cie1: 15,
    cie2: 17,
    labOrQuiz: 12,
    totalCIE: 28,
    remarks: 'Attendance critical warning issued',
  },
  {
    id: 's6',
    usn: '1MS24CS006',
    name: 'Sneha Kulkarni',
    email: 'sneha.k@univ.edu',
    courseCode: 'CS201',
    attendancePercent: 85,
    classesHeld: 40,
    classesAttended: 34,
    cie1: 24,
    cie2: 25,
    labOrQuiz: 17,
    totalCIE: 42,
  },
  {
    id: 's7',
    usn: '1MS24CS007',
    name: 'Mohammed Zaid',
    email: 'm.zaid@univ.edu',
    courseCode: 'CS201',
    attendancePercent: 82,
    classesHeld: 40,
    classesAttended: 33,
    cie1: 22,
    cie2: 23,
    labOrQuiz: 16,
    totalCIE: 39,
  },
  {
    id: 's8',
    usn: '1MS24CS008',
    name: 'Pooja Reddy',
    email: 'pooja.reddy@univ.edu',
    courseCode: 'CS201',
    attendancePercent: 90,
    classesHeld: 40,
    classesAttended: 36,
    cie1: 26,
    cie2: 27,
    labOrQuiz: 18,
    totalCIE: 45,
  },
];

export const INITIAL_FACULTY_CIE_PAPERS: FacultyCIEPaper[] = [
  {
    id: 'CIE-CS201-TEST1',
    courseCode: 'CS201',
    courseTitle: 'Data Structures & Algorithms',
    semester: '3rd Sem B.Tech',
    testType: 'CIE-1',
    maxMarks: 30,
    status: 'SUBMITTED_TO_HOD',
    submittedAt: '2026-09-02 11:30 AM',
    questions: [
      { id: 'q1', qNumber: '1a', text: 'Define Big-O notation and compute tight bound for binary search recurrence T(n) = T(n/2) + O(1).', marks: 5, bloomsLevel: 'L2', co: 'CO1' },
      { id: 'q2', qNumber: '1b', text: 'Implement a circular queue using a fixed-size array and explain underflow/overflow handling.', marks: 10, bloomsLevel: 'L3', co: 'CO2' },
      { id: 'q3', qNumber: '2a', text: 'Given sequence [12, 11, 13, 5, 6, 7], construct a max-heap step-by-step and show the array representation.', marks: 8, bloomsLevel: 'L3', co: 'CO2' },
      { id: 'q4', qNumber: '2b', text: 'Differentiate between BFS and DFS traversal in terms of auxiliary memory requirements.', marks: 7, bloomsLevel: 'L4', co: 'CO3' },
    ]
  },
  {
    id: 'CIE-CS303-TEST1',
    courseCode: 'CS303',
    courseTitle: 'Computer Networks & Protocols',
    semester: '5th Sem B.Tech',
    testType: 'CIE-1',
    maxMarks: 30,
    status: 'DRAFT',
    questions: [
      { id: 'q20', qNumber: '1', text: 'Explain the 7 layers of ISO-OSI model with data unit encapsulation headers.', marks: 10, bloomsLevel: 'L2', co: 'CO1' },
      { id: 'q21', qNumber: '2', text: 'Calculate the CRC checksum for data word 1101001110 with generator polynomial x^4 + x + 1.', marks: 10, bloomsLevel: 'L3', co: 'CO2' },
      { id: 'q22', qNumber: '3', text: 'Describe the 3-way handshake in TCP connection establishment and teardown.', marks: 10, bloomsLevel: 'L2', co: 'CO3' },
    ]
  }
];
