import 'models/student_models.dart';

final mockStudentProfile = StudentProfile(
  usn: '1NX22CS001',
  fullName: 'Aarav Sharma',
  program: 'B.Tech in Computer Science & Engineering',
  semester: '6th Semester',
  section: 'Section A',
  cgpa: 8.92,
  latestSgpa: 9.14,
  avatarInitials: 'AS',
);

final mockExamSchedule = [
  ExamScheduleItem(
    courseCode: 'CS201',
    courseTitle: 'Data Structures & Algorithms',
    examDate: 'August 31, 2026',
    timeSlot: '09:30 AM – 12:30 PM IST',
    hallNumber: 'Exam Hall B-104 (CS Block)',
    deskNumber: 'Desk B-01',
    eligibilityStatus: 'ELIGIBLE',
    isCompleted: false,
    qrPayload: 'NEXAI_ADMIT_1NX22CS001_CS201_B104_B01_SIG9842',
  ),
  ExamScheduleItem(
    courseCode: 'CS301',
    courseTitle: 'Operating Systems',
    examDate: 'September 02, 2026',
    timeSlot: '09:30 AM – 12:30 PM IST',
    hallNumber: 'Exam Hall A-202 (Main Block)',
    deskNumber: 'Desk A-14',
    eligibilityStatus: 'ELIGIBLE',
    isCompleted: false,
    qrPayload: 'NEXAI_ADMIT_1NX22CS001_CS301_A202_A14_SIG9843',
  ),
  ExamScheduleItem(
    courseCode: 'CS302',
    courseTitle: 'Database Management Systems',
    examDate: 'September 04, 2026',
    timeSlot: '02:00 PM – 05:00 PM IST',
    hallNumber: 'Exam Hall C-101 (IT Block)',
    deskNumber: 'Desk C-09',
    eligibilityStatus: 'ELIGIBLE',
    isCompleted: false,
    qrPayload: 'NEXAI_ADMIT_1NX22CS001_CS302_C101_C09_SIG9844',
  ),
];

final mockExamResults = [
  ExamResultItem(
    courseCode: 'CS101',
    courseTitle: 'Design and Analysis of Algorithms',
    credits: 4,
    gradeLetter: 'S',
    cieMarks: 48,
    seeMarks: 46,
    totalMarks: 94,
    scriptPagesCount: 8,
    isRevaluationApplied: false,
  ),
  ExamResultItem(
    courseCode: 'CS102',
    courseTitle: 'Computer Networks & Security',
    credits: 4,
    gradeLetter: 'A',
    cieMarks: 42,
    seeMarks: 42,
    totalMarks: 84,
    scriptPagesCount: 8,
    isRevaluationApplied: false,
  ),
  ExamResultItem(
    courseCode: 'CS103',
    courseTitle: 'Software Engineering & Agile',
    credits: 3,
    gradeLetter: 'B',
    cieMarks: 38,
    seeMarks: 38,
    totalMarks: 76,
    scriptPagesCount: 6,
    isRevaluationApplied: false,
  ),
  ExamResultItem(
    courseCode: 'MA201',
    courseTitle: 'Discrete Mathematical Structures',
    credits: 4,
    gradeLetter: 'S',
    cieMarks: 49,
    seeMarks: 47,
    totalMarks: 96,
    scriptPagesCount: 8,
    isRevaluationApplied: false,
  ),
];

final mockSandboxQuestions = [
  ExamQuestionItem(
    questionNumber: 1,
    questionText: 'What is the worst-case time complexity of searching for an element in an un-balanced Binary Search Tree (BST)?',
    maxMarks: 5,
    type: 'MCQ',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    candidateAnswer: 'O(n)',
    isAnswered: true,
  ),
  ExamQuestionItem(
    questionNumber: 2,
    questionText: 'Differentiate between Dijkstra\'s Shortest Path Algorithm and Bellman-Ford Algorithm with respect to negative edge weights.',
    maxMarks: 10,
    type: 'THEORY',
    candidateAnswer: 'Dijkstra fails on graphs with negative edge weight cycles, whereas Bellman-Ford detects negative weight cycles with O(V*E) complexity.',
    isAnswered: true,
  ),
  ExamQuestionItem(
    questionNumber: 3,
    questionText: 'Write the recurrence relation for the Merge Sort algorithm and solve it using Master Theorem.',
    maxMarks: 10,
    type: 'THEORY',
    candidateAnswer: 'T(n) = 2T(n/2) + O(n). By Master Theorem Case 2, T(n) = O(n log n).',
    isAnswered: true,
  ),
  ExamQuestionItem(
    questionNumber: 4,
    questionText: 'Implement the partition step of Quicksort (Lomuto or Hoare partition scheme) in Python or Java.',
    maxMarks: 15,
    type: 'CODE',
    candidateAnswer: 'def partition(arr, low, high):\n    pivot = arr[high]\n    i = low - 1\n    for j in range(low, high):\n        if arr[j] <= pivot:\n            i += 1\n            arr[i], arr[j] = arr[j], arr[i]\n    arr[i+1], arr[high] = arr[high], arr[i+1]\n    return i + 1',
    isAnswered: true,
  ),
];

final mockRegisteredCourses = [
  CourseAttendanceCieItem(
    courseCode: 'CS201',
    courseTitle: 'Data Structures & Algorithms',
    facultyName: 'Dr. Ramesh Kulkarni (Prof & HOD)',
    credits: 4,
    attendedClasses: 43,
    totalClasses: 48,
    cie1Marks: 19.5,
    cie2Marks: 18.0,
    cie3Marks: 19.0,
    assignmentMarks: 9.5,
    totalCieMarks: 47.0,
  ),
  CourseAttendanceCieItem(
    courseCode: 'CS301',
    courseTitle: 'Operating Systems',
    facultyName: 'Dr. Ananya Sen (Assoc. Prof)',
    credits: 4,
    attendedClasses: 40,
    totalClasses: 46,
    cie1Marks: 17.5,
    cie2Marks: 18.5,
    cie3Marks: 16.0,
    assignmentMarks: 9.0,
    totalCieMarks: 45.0,
  ),
  CourseAttendanceCieItem(
    courseCode: 'CS302',
    courseTitle: 'Database Management Systems',
    facultyName: 'Prof. Vikram Hegde',
    credits: 4,
    attendedClasses: 36,
    totalClasses: 44,
    cie1Marks: 16.0,
    cie2Marks: 17.0,
    cie3Marks: 18.0,
    assignmentMarks: 8.5,
    totalCieMarks: 42.5,
  ),
  CourseAttendanceCieItem(
    courseCode: 'CS303',
    courseTitle: 'Computer Networks & Security',
    facultyName: 'Dr. Priya Nambiar',
    credits: 3,
    attendedClasses: 32,
    totalClasses: 40,
    cie1Marks: 15.0,
    cie2Marks: 16.5,
    cie3Marks: 17.0,
    assignmentMarks: 8.0,
    totalCieMarks: 40.0,
  ),
  CourseAttendanceCieItem(
    courseCode: 'CS304',
    courseTitle: 'Artificial Intelligence & Expert Systems',
    facultyName: 'Dr. S. Sundaram',
    credits: 3,
    attendedClasses: 37,
    totalClasses: 42,
    cie1Marks: 19.0,
    cie2Marks: 19.5,
    cie3Marks: 18.5,
    assignmentMarks: 10.0,
    totalCieMarks: 48.5,
  ),
  CourseAttendanceCieItem(
    courseCode: 'CS305L',
    courseTitle: 'Advanced Data Structures & Algorithms Lab',
    facultyName: 'Prof. Sneha Deshmukh',
    credits: 2,
    attendedClasses: 28,
    totalClasses: 30,
    cie1Marks: 20.0,
    cie2Marks: 19.0,
    cie3Marks: 20.0,
    assignmentMarks: 10.0,
    totalCieMarks: 49.0,
  ),
];
