[pytest]
DJANGO_SETTINGS_MODULE = config.settings.testing
python_files = tests_*.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --color=yes -p no:warnings
