import { QuestionPaperSet, VaultSubject, SessionKeyData } from './types';

export const INITIAL_SUBJECTS: VaultSubject[] = [
  {
    code: 'CS201',
    title: 'Data Structures & Algorithms',
    department: 'Computer Science',
    examDate: 'Oct 15, 2026',
    examSlot: '10:00 AM - 01:00 PM',
    setsAvailable: 4,
    requiredSets: 4,
    vaultStatus: 'KEY_GENERATED',
    activeSelectedSetId: undefined,
  },
  {
    code: 'CS101',
    title: 'Introduction to Computer Science',
    department: 'Computer Science',
    examDate: 'Oct 16, 2026',
    examSlot: '02:00 PM - 05:00 PM',
    setsAvailable: 3,
    requiredSets: 3,
    vaultStatus: 'LOCKED',
  },
  {
    code: 'CS301',
    title: 'Operating Systems',
    department: 'Computer Science',
    examDate: 'Oct 18, 2026',
    examSlot: '10:00 AM - 01:00 PM',
    setsAvailable: 4,
    requiredSets: 4,
    vaultStatus: 'UNSEALED',
    activeSelectedSetId: 'CS301-SET-B',
  },
  {
    code: 'MA101',
    title: 'Engineering Mathematics I',
    department: 'Mathematics',
    examDate: 'Oct 20, 2026',
    examSlot: '10:00 AM - 01:00 PM',
    setsAvailable: 2,
    requiredSets: 3,
    vaultStatus: 'LOCKED',
  },
];

export const INITIAL_PAPERS: QuestionPaperSet[] = [
  // CS201 Sets
  {
    id: 'CS201-SET-A',
    setLabel: 'Set A',
    title: 'Data Structures & Algorithms - End Semester',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    examSession: 'Fall 2026',
    semester: '3rd Semester B.Tech',
    setterName: 'Dr. Alan Turing (Setter #104)',
    setterDepartment: 'Department of Computer Science',
    status: 'VAULTED',
    ipfsCid: 'QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco',
    sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    submittedAt: '2026-08-28 14:30 IST',
    difficulty: 'Balanced',
    aiQualityScore: 96,
    similarityScore: 1.8,
    totalMarks: 100,
    durationMinutes: 180,
    questionsCount: 8,
    questions: [
      { id: 'q1', number: 1, section: 'Part A', text: 'Define Big-O, Omega, and Theta asymptotic notations with formal mathematical bounds and graphical interpretations.', marks: 10, bloomsLevel: 'Understand', coMapping: 'CO1' },
      { id: 'q2', number: 2, section: 'Part A', text: 'Explain the difference between linear probing, quadratic probing, and double hashing in hash collision resolution.', marks: 10, bloomsLevel: 'Understand', coMapping: 'CO2' },
      { id: 'q3', number: 3, section: 'Part B', text: 'Implement an algorithm for AVL tree self-balancing rotations (LL, RR, LR, RL) with balance factor recomputation.', marks: 15, bloomsLevel: 'Apply', coMapping: 'CO3' },
      { id: 'q4', number: 4, section: 'Part B', text: 'Construct a Red-Black tree by inserting the following sequence: [23, 12, 45, 67, 34, 89, 5]. Show tree recoloring and rotation steps.', marks: 15, bloomsLevel: 'Apply', coMapping: 'CO3' },
      { id: 'q5', number: 5, section: 'Part C', text: 'Design and analyze Dijkstra’s Single Source Shortest Path algorithm using a Fibonacci Heap vs Binary Min-Heap priority queue.', marks: 15, bloomsLevel: 'Analyze', coMapping: 'CO4' },
      { id: 'q6', number: 6, section: 'Part C', text: 'Formulate a Dynamic Programming approach to solve the 0/1 Knapsack problem. Derive time and space complexities.', marks: 15, bloomsLevel: 'Evaluate', coMapping: 'CO5' },
      { id: 'q7', number: 7, section: 'Part D', text: 'Prove the Lower Bound theorem for comparison-based sorting algorithms: Omega(n log n).', marks: 10, bloomsLevel: 'Analyze', coMapping: 'CO1' },
      { id: 'q8', number: 8, section: 'Part D', text: 'Synthesize a spatial indexing structure (R-Tree / KD-Tree) for multi-dimensional range queries in geographical databases.', marks: 10, bloomsLevel: 'Create', coMapping: 'CO6' },
    ],
  },
  {
    id: 'CS201-SET-B',
    setLabel: 'Set B',
    title: 'Data Structures & Algorithms - End Semester',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    examSession: 'Fall 2026',
    semester: '3rd Semester B.Tech',
    setterName: 'Prof. Donald Knuth (Setter #108)',
    setterDepartment: 'Department of Computer Science',
    status: 'VAULTED',
    ipfsCid: 'QmZ4tDuvesekSs4qM5ZBKpXiZGun7S2CYtEZRB3DYXkjGx',
    sha256Hash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    submittedAt: '2026-08-29 11:15 IST',
    difficulty: 'Challenging',
    aiQualityScore: 98,
    similarityScore: 0.9,
    totalMarks: 100,
    durationMinutes: 180,
    questionsCount: 8,
    questions: [
      { id: 'q1', number: 1, section: 'Part A', text: 'Derive the Master Theorem recurrence relation for T(n) = 3T(n/2) + O(n log n).', marks: 10, bloomsLevel: 'Analyze', coMapping: 'CO1' },
      { id: 'q2', number: 2, section: 'Part A', text: 'Explain Skip Lists and analyze the expected time complexity for search, insertion, and deletion operations.', marks: 10, bloomsLevel: 'Understand', coMapping: 'CO2' },
      { id: 'q3', number: 3, section: 'Part B', text: 'Develop an in-place Quickselect algorithm to find the k-th smallest element in O(n) expected time.', marks: 15, bloomsLevel: 'Apply', coMapping: 'CO3' },
      { id: 'q4', number: 4, section: 'Part B', text: 'Demonstrate B-Tree node splitting and merging for degree t=3 upon sequential insertions: [10, 20, 30, 40, 50, 60, 70, 80].', marks: 15, bloomsLevel: 'Apply', coMapping: 'CO3' },
      { id: 'q5', number: 5, section: 'Part C', text: 'Implement Tarjan’s algorithm for Strongly Connected Components (SCC) using Depth First Search traversal stack.', marks: 15, bloomsLevel: 'Analyze', coMapping: 'CO4' },
      { id: 'q6', number: 6, section: 'Part C', text: 'Design the A* search heuristic function for 15-puzzle state space exploration. Prove admissibility and consistency.', marks: 15, bloomsLevel: 'Evaluate', coMapping: 'CO5' },
      { id: 'q7', number: 7, section: 'Part D', text: 'Analyze Bellman-Ford Negative Cycle Detection algorithm and its application in distributed routing protocols.', marks: 10, bloomsLevel: 'Analyze', coMapping: 'CO4' },
      { id: 'q8', number: 8, section: 'Part D', text: 'Architect a Trie-based autocomplete and spell-checker engine handling 10 million words with prefix frequency weights.', marks: 10, bloomsLevel: 'Create', coMapping: 'CO6' },
    ],
  },
  {
    id: 'CS201-SET-C',
    setLabel: 'Set C',
    title: 'Data Structures & Algorithms - End Semester',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    examSession: 'Fall 2026',
    semester: '3rd Semester B.Tech',
    setterName: 'Dr. Barbara Liskov (Setter #112)',
    setterDepartment: 'Department of Computer Science',
    status: 'VAULTED',
    ipfsCid: 'QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG',
    sha256Hash: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
    submittedAt: '2026-08-30 09:40 IST',
    difficulty: 'Moderate',
    aiQualityScore: 94,
    similarityScore: 2.1,
    totalMarks: 100,
    durationMinutes: 180,
    questionsCount: 8,
    questions: [
      { id: 'q1', number: 1, section: 'Part A', text: 'Differentiate between amortized time complexity and worst-case time complexity using Dynamic Array doubling as a case study.', marks: 10, bloomsLevel: 'Understand', coMapping: 'CO1' },
      { id: 'q2', number: 2, section: 'Part A', text: 'Explain the working principle of Disjoint Set Union (DSU) with Union by Rank and Path Compression optimizations.', marks: 10, bloomsLevel: 'Understand', coMapping: 'CO2' },
      { id: 'q3', number: 3, section: 'Part B', text: 'Write a non-recursive algorithm for Binary Search Tree in-order traversal using an explicit Stack.', marks: 15, bloomsLevel: 'Apply', coMapping: 'CO3' },
      { id: 'q4', number: 4, section: 'Part B', text: 'Construct a Minimum Spanning Tree for a given weighted graph using Kruskal’s and Prim’s algorithms. Compare step counts.', marks: 15, bloomsLevel: 'Apply', coMapping: 'CO4' },
      { id: 'q5', number: 5, section: 'Part C', text: 'Formulate the Floyd-Warshall All-Pairs Shortest Path algorithm. Analyze matrix state transitions.', marks: 15, bloomsLevel: 'Analyze', coMapping: 'CO4' },
      { id: 'q6', number: 6, section: 'Part C', text: 'Solve the Matrix Chain Multiplication problem using dynamic programming memoization table.', marks: 15, bloomsLevel: 'Evaluate', coMapping: 'CO5' },
      { id: 'q7', number: 7, section: 'Part D', text: 'Explain Topological Sorting on Directed Acyclic Graphs (DAG) and its use in compiler build dependency resolution.', marks: 10, bloomsLevel: 'Analyze', coMapping: 'CO4' },
      { id: 'q8', number: 8, section: 'Part D', text: 'Design a LRU Cache data structure supporting O(1) get() and put() using Doubly Linked List and Hash Map.', marks: 10, bloomsLevel: 'Create', coMapping: 'CO6' },
    ],
  },
  {
    id: 'CS201-SET-D',
    setLabel: 'Set D',
    title: 'Data Structures & Algorithms - End Semester',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    examSession: 'Fall 2026',
    semester: '3rd Semester B.Tech',
    setterName: 'Prof. Edsger Dijkstra (Setter #119)',
    setterDepartment: 'Department of Computer Science',
    status: 'VAULTED',
    ipfsCid: 'QmV5Xw6fE82K97oJ7C2zE8v11fK72kK8N2N6X6K94u3W21',
    sha256Hash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
    submittedAt: '2026-08-30 16:20 IST',
    difficulty: 'Challenging',
    aiQualityScore: 97,
    similarityScore: 1.2,
    totalMarks: 100,
    durationMinutes: 180,
    questionsCount: 8,
    questions: [
      { id: 'q1', number: 1, section: 'Part A', text: 'Analyze Huffman Coding greedy algorithm for lossless prefix compression. Prove greedy choice property.', marks: 10, bloomsLevel: 'Analyze', coMapping: 'CO1' },
      { id: 'q2', number: 2, section: 'Part A', text: 'Explain Treap (Tree + Heap) randomized binary search tree properties and average tree height.', marks: 10, bloomsLevel: 'Understand', coMapping: 'CO2' },
      { id: 'q3', number: 3, section: 'Part B', text: 'Construct a Segment Tree with Lazy Propagation supporting range sum queries and range addition updates in O(log n).', marks: 15, bloomsLevel: 'Apply', coMapping: 'CO3' },
      { id: 'q4', number: 4, section: 'Part B', text: 'Solve the Maximum Flow problem using the Ford-Fulkerson algorithm with Edmonds-Karp BFS augmenting paths.', marks: 15, bloomsLevel: 'Analyze', coMapping: 'CO4' },
      { id: 'q5', number: 5, section: 'Part C', text: 'Develop the KMP (Knuth-Morris-Pratt) string matching algorithm with Pi failure function table computation.', marks: 15, bloomsLevel: 'Apply', coMapping: 'CO5' },
      { id: 'q6', number: 6, section: 'Part C', text: 'Evaluate Suffix Automaton vs Suffix Tree for multi-pattern substring occurrence counting in genomic sequences.', marks: 15, bloomsLevel: 'Evaluate', coMapping: 'CO5' },
      { id: 'q7', number: 7, section: 'Part D', text: 'Formulate Ford-Warshall vs Johnson’s algorithm for sparse graph all-pairs shortest paths with reweighting.', marks: 10, bloomsLevel: 'Analyze', coMapping: 'CO4' },
      { id: 'q8', number: 8, section: 'Part D', text: 'Design a Persistent Segment Tree supporting historical point updates and version-checkpoint queries in O(log n).', marks: 10, bloomsLevel: 'Create', coMapping: 'CO6' },
    ],
  },
  // CS301 (Unsealed Sample)
  {
    id: 'CS301-SET-B',
    setLabel: 'Set B',
    title: 'Operating Systems - End Semester Final',
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems',
    examSession: 'Fall 2026',
    semester: '5th Semester B.Tech',
    setterName: 'Dr. Linus Torvalds (Setter #102)',
    setterDepartment: 'Department of Computer Science',
    status: 'SELECTED_ACTIVE',
    ipfsCid: 'QmUBf8vD9fJzX9ZqK7L98z22A2bK97N2N6X6K94u3W21AA',
    sha256Hash: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
    submittedAt: '2026-08-25 10:00 IST',
    difficulty: 'Balanced',
    aiQualityScore: 99,
    similarityScore: 0.5,
    totalMarks: 100,
    durationMinutes: 180,
    questionsCount: 6,
    questions: [
      { id: 'os1', number: 1, section: 'Part A', text: 'Explain the 5-state process lifecycle and describe the exact Context Switch procedure including register dumping and TLB invalidation.', marks: 15, bloomsLevel: 'Understand', coMapping: 'CO1' },
      { id: 'os2', number: 2, section: 'Part A', text: 'Solve synchronization using Peterson’s Algorithm for two processes. Prove mutual exclusion, progress, and bounded waiting.', marks: 15, bloomsLevel: 'Analyze', coMapping: 'CO2' },
      { id: 'os3', number: 3, section: 'Part B', text: 'Execute Banker’s Algorithm for Deadlock Avoidance on a given Resource Allocation state with Allocation, Max, and Available matrices.', marks: 20, bloomsLevel: 'Apply', coMapping: 'CO3' },
      { id: 'os4', number: 4, section: 'Part B', text: 'Contrast Multi-Level Paging with Inverted Page Tables. Calculate effective memory access time with TLB hit ratio alpha=0.92.', marks: 20, bloomsLevel: 'Evaluate', coMapping: 'CO4' },
      { id: 'os5', number: 5, section: 'Part C', text: 'Evaluate LRU, FIFO, and Optimal Page Replacement algorithms on a reference string: [7,0,1,2,0,3,0,4,2,3,0,3,2,1,2,0,1,7,0,1] with 3 frames.', marks: 15, bloomsLevel: 'Analyze', coMapping: 'CO4' },
      { id: 'os6', number: 6, section: 'Part C', text: 'Design a Crash-Consistent Journaling File System architecture (Write-Ahead Logging) for atomic multi-block disk writes.', marks: 15, bloomsLevel: 'Create', coMapping: 'CO5' },
    ],
  },
];

export const MOCK_SESSION_KEYS: Record<string, SessionKeyData> = {
  'CS201': {
    keyId: 'KEY-2026-CS201-9981',
    subjectCode: 'CS201',
    algorithm: 'AES-256-GCM + CRYSTALS-Dilithium3 Signature',
    generatedAt: '2026-08-31 11:20 IST',
    expiresAt: '2026-10-15 13:30 IST',
    unlockTimestamp: '2026-10-15 09:30 IST (30 mins before exam)',
    thresholdQuorum: {
      required: 2,
      total: 3,
      signed: ['Controller of Examinations', 'Chief Superintendent'],
    },
    keyFingerprint: '9E:B4:7C:11:8A:2F:90:3D:5E:21:44:BC:77:E1:60:FA',
    isUnlocked: false,
  },
  'CS301': {
    keyId: 'KEY-2026-CS301-7712',
    subjectCode: 'CS301',
    algorithm: 'AES-256-GCM + CRYSTALS-Dilithium3 Signature',
    generatedAt: '2026-08-30 09:15 IST',
    expiresAt: '2026-10-18 13:30 IST',
    unlockTimestamp: '2026-10-18 09:30 IST',
    thresholdQuorum: {
      required: 2,
      total: 3,
      signed: ['Controller of Examinations', 'Chief Superintendent', 'University Observer'],
    },
    keyFingerprint: '4A:77:2C:99:0B:E1:5D:88:3F:12:9A:CD:E4:01:88:1C',
    isUnlocked: true,
  },
};
