# Generated by Django 6.1 on 2026-08-31 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('VAULT_UNLOCK', 'Question Paper Vault Unlocked'), ('PAPER_APPROVED', 'Question Paper Approved'), ('GRADE_OVERRIDE', 'Student Grade Overridden'), ('ELIGIBILITY_UPDATE', 'Student Eligibility Mass Updated'), ('SYSTEM_CONFIG', 'System Configuration Changed')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('details', models.JSONField(default=dict, help_text='Additional metadata regarding the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
