import { ScrutinyBundle, EvaluatorProfile } from './types';

export const INITIAL_EVALUATORS: EvaluatorProfile[] = [
  {
    id: 'eval_1',
    facultyId: 'FAC_104',
    name: 'Dr. Alan Turing',
    department: 'Department of Computer Science',
    designation: 'Professor & Senior Valuer',
    email: 'alan.turing@univ.edu',
    phone: '+91 98450 12345',
    experienceYears: 18,
    assignedBundlesCount: 1,
    maxBundleQuota: 3,
    valuationCenterLab: 'Valuation Lab B-14',
  },
  {
    id: 'eval_2',
    facultyId: 'FAC_108',
    name: 'Dr. Barbara Liskov',
    department: 'Department of Computer Science',
    designation: 'Associate Professor',
    email: 'b.liskov@univ.edu',
    phone: '+91 98450 23456',
    experienceYears: 12,
    assignedBundlesCount: 2,
    maxBundleQuota: 3,
    valuationCenterLab: 'Valuation Lab B-14',
  },
  {
    id: 'eval_3',
    facultyId: 'FAC_112',
    name: 'Prof. Donald Knuth',
    department: 'Department of Computer Science',
    designation: 'Visiting Professor & Chief Referee',
    email: 'd.knuth@univ.edu',
    phone: '+91 98450 34567',
    experienceYears: 25,
    assignedBundlesCount: 0,
    maxBundleQuota: 2,
    valuationCenterLab: 'Valuation Lab A-02',
  },
  {
    id: 'eval_4',
    facultyId: 'FAC_119',
    name: 'Dr. Edsger Dijkstra',
    department: 'Department of Information Science',
    designation: 'Professor of Algorithms',
    email: 'e.dijkstra@univ.edu',
    phone: '+91 98450 45678',
    experienceYears: 20,
    assignedBundlesCount: 1,
    maxBundleQuota: 3,
    valuationCenterLab: 'Valuation Lab B-14',
  },
];

export const INITIAL_SCRUTINY_BUNDLES: ScrutinyBundle[] = [
  {
    id: 'BUN_001',
    bundleCode: 'BUNDLE-CS201-01',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    semester: '3rd Semester B.Tech',
    examSession: 'Fall End-Semester 2026',
    examDate: '2026-08-25',
    totalScripts: 40,
    completedScripts: 40,
    assignedEvaluatorId: 'eval_1',
    assignedEvaluatorName: 'Dr. Alan Turing',
    valuationDeadline: '2026-09-02',
    status: 'EVALUATED_PENDING_SCRUTINY',
    scrutinyStatus: 'IN_SCRUTINY',
    auditedScriptsCount: 38,
    scripts: [
      {
        id: 'scr_1',
        dummyBarcode: 'ANON-CS201-8940',
        bundleId: 'BUN_001',
        subjectCode: 'CS201',
        totalPages: 8,
        frontPageTotal: 91,
        summedQuestionMarks: 91,
        evaluatorName: 'Dr. Alan Turing',
        status: 'VERIFIED_ACCURATE',
        isAudited: true,
      },
      {
        id: 'scr_2',
        dummyBarcode: 'ANON-CS201-8941',
        bundleId: 'BUN_001',
        subjectCode: 'CS201',
        totalPages: 8,
        frontPageTotal: 76,
        summedQuestionMarks: 78,
        evaluatorName: 'Dr. Alan Turing',
        status: 'ARITHMETIC_MISMATCH_DETECTED',
        discrepancyDetails: 'Cover page grand total written as 76, but inside questions sum is 78 (Q1: 10 + Q2: 18 + Q3: 20 + Q4: 15 + Q5: 15 = 78).',
        scrutinizerCorrectedScore: 78,
        scrutinizerNotes: 'Totaling slip of +2 marks verified and updated.',
        isAudited: true,
      },
      {
        id: 'scr_3',
        dummyBarcode: 'ANON-CS201-8942',
        bundleId: 'BUN_001',
        subjectCode: 'CS201',
        totalPages: 8,
        frontPageTotal: 42,
        summedQuestionMarks: 42,
        evaluatorName: 'Dr. Alan Turing',
        status: 'VERIFIED_ACCURATE',
        isAudited: true,
      },
      {
        id: 'scr_4',
        dummyBarcode: 'ANON-CS201-8943',
        bundleId: 'BUN_001',
        subjectCode: 'CS201',
        totalPages: 8,
        frontPageTotal: 84,
        summedQuestionMarks: 84,
        evaluatorName: 'Dr. Alan Turing',
        status: 'VERIFIED_ACCURATE',
        isAudited: false,
      },
    ],
  },
  {
    id: 'BUN_002',
    bundleCode: 'BUNDLE-CS201-02',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    semester: '3rd Semester B.Tech',
    examSession: 'Fall End-Semester 2026',
    examDate: '2026-08-25',
    totalScripts: 40,
    completedScripts: 0,
    assignedEvaluatorId: undefined,
    assignedEvaluatorName: undefined,
    valuationDeadline: '2026-09-05',
    status: 'UNASSIGNED',
    scrutinyStatus: 'PENDING',
    auditedScriptsCount: 0,
    scripts: [],
  },
  {
    id: 'BUN_003',
    bundleCode: 'BUNDLE-CS301-01',
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems',
    semester: '5th Semester B.Tech',
    examSession: 'Fall End-Semester 2026',
    examDate: '2026-08-26',
    totalScripts: 35,
    completedScripts: 22,
    assignedEvaluatorId: 'eval_2',
    assignedEvaluatorName: 'Dr. Barbara Liskov',
    valuationDeadline: '2026-09-06',
    status: 'IN_EVALUATION',
    scrutinyStatus: 'PENDING',
    auditedScriptsCount: 0,
    scripts: [],
  },
  {
    id: 'BUN_004',
    bundleCode: 'BUNDLE-CS401-01',
    subjectCode: 'CS401',
    subjectTitle: 'Distributed Systems & Cloud Computing',
    semester: '7th Semester B.Tech',
    examSession: 'Fall End-Semester 2026',
    examDate: '2026-08-27',
    totalScripts: 30,
    completedScripts: 30,
    assignedEvaluatorId: 'eval_4',
    assignedEvaluatorName: 'Dr. Edsger Dijkstra',
    valuationDeadline: '2026-09-01',
    status: 'SCRUTINIZED_AND_SEALED',
    scrutinyStatus: 'CERTIFIED',
    auditedScriptsCount: 30,
    scripts: [],
  },
];
