# Generated by Django 6.0.8 on 2026-08-31 05:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Nov-Dec 2024 SEE', max_length=200)),
                ('semester', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(help_text='e.g. 2024-25', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Timetable Generated'), ('ACTIVE', 'Exams In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=15)),
                ('scheduling_task_id', models.CharField(blank=True, help_text='Celery task ID for OR-Tools scheduling run', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduling_exam_session',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InvigilationDuty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duty_role', models.CharField(choices=[('CHIEF', 'Chief Invigilator'), ('RELIEF', 'Relief Invigilator')], default='CHIEF', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scheduling_invigilation_duty',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Room 101', max_length=100, unique=True)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.PositiveSmallIntegerField(default=0)),
                ('total_capacity', models.PositiveSmallIntegerField()),
                ('exam_capacity', models.PositiveSmallIntegerField(help_text='Max students allowed during an exam (usually 60–70% of total)')),
                ('has_cctv', models.BooleanField(default=True)),
                ('has_wifi', models.BooleanField(default=False)),
                ('is_lab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scheduling_room',
                'ordering': ['building', 'floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scheduling_student_subject_enrollment',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. CS601', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('subject_type', models.CharField(choices=[('CORE', 'Core Subject'), ('ELECTIVE', 'Elective Subject'), ('LAB', 'Laboratory / Practical'), ('PROJECT', 'Project / Seminar')], default='CORE', max_length=10)),
                ('semester', models.PositiveSmallIntegerField(help_text='Semester number (1–8)', validators=[django.core.validators.MinValueValidator(1)])),
                ('credits', models.PositiveSmallIntegerField(default=4)),
                ('batch_year', models.PositiveSmallIntegerField(help_text='Batch year this subject applies to (e.g. 2022)')),
                ('exam_duration_mins', models.PositiveSmallIntegerField(default=180, help_text='SEE exam duration in minutes (default 3 hours)')),
                ('co_list', models.JSONField(default=list, help_text="List of CO codes, e.g. ['CO1','CO2','CO3']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduling_subject',
                'ordering': ['semester', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=15)),
                ('solver_score', models.FloatField(blank=True, help_text='Objective score from OR-Tools solver for this slot', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scheduling_timetable_slot',
                'ordering': ['exam_date', 'start_time'],
            },
        ),
    ]
