# Generated by Django 6.0.8 on 2026-08-31 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invigilationduty',
            name='invigilator',
            field=models.ForeignKey(limit_choices_to={'role__in': ['INVIGILATOR', 'HOD', 'EVALUATOR']}, on_delete=django.db.models.deletion.PROTECT, related_name='invigilation_duties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='scheduling.examsession'),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='users.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='users.department'),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='scheduling.subject'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='scheduling.examsession'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='scheduling.room'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='scheduling.subject'),
        ),
        migrations.AddField(
            model_name='invigilationduty',
            name='timetable_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation_duties', to='scheduling.timetableslot'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'batch_year')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectenrollment',
            unique_together={('student', 'subject', 'exam_session')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('room', 'exam_date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='invigilationduty',
            unique_together={('timetable_slot', 'invigilator')},
        ),
    ]
