# Generated by Django 6.1 on 2026-08-31 04:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('qr_code_data', models.TextField(blank=True, help_text='Data encoded in the QR code (or URL to the QR image)')),
                ('is_revoked', models.BooleanField(default=False, help_text='If true, the hall ticket is invalid')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='scheduling.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='users.student')),
            ],
            options={
                'db_table': 'nexai_hall_ticket',
                'unique_together': {('student', 'exam_session')},
            },
        ),
        migrations.CreateModel(
            name='StudentEligibility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Attendance percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cie_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Continuous Internal Evaluation marks', max_digits=5, null=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, help_text="System or manual remarks (e.g. 'Shortage of attendance')")),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_records', to='scheduling.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_records', to='users.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_records', to='scheduling.subject')),
            ],
            options={
                'verbose_name_plural': 'Student Eligibilities',
                'db_table': 'nexai_eligibility',
                'unique_together': {('student', 'subject', 'exam_session')},
            },
        ),
    ]
