# Generated by Django 6.1 on 2026-08-31 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cie_marks', models.DecimalField(decimal_places=2, default=0.0, help_text='Continuous Internal Evaluation Marks', max_digits=5)),
                ('see_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Semester End Examination Marks', max_digits=5, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, choices=[('S', 'Outstanding (90-100)'), ('A', 'Excellent (80-89)'), ('B', 'Very Good (70-79)'), ('C', 'Good (60-69)'), ('D', 'Above Average (50-59)'), ('E', 'Average (40-49)'), ('F', 'Fail (<40)'), ('ABSENT', 'Absent')], max_length=6, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scheduling.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='users.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scheduling.subject')),
            ],
            options={
                'db_table': 'student_result',
                'unique_together': {('student', 'subject', 'exam_session')},
            },
        ),
    ]
