import 'models/exam_models.dart';

final INITIAL_STUDENTS = [
  StudentDeskItem(
    deskId: 'Desk B-01',
    usn: '1NX22CS001',
    studentName: 'Aarav Sharma',
    courseCode: 'CS201',
    seatPosition: 'Row 1, Col 1',
    isQrVerified: true,
    isBiometricMatched: true,
    status: StudentAttendanceStatus.present,
    bookletBarcode: 'BC-990142',
    dummyBarcode: 'ANON-CS201-8940',
    digitizedPagesCount: 16,
    avatarInitials: 'AS',
  ),
  StudentDeskItem(
    deskId: 'Desk B-02',
    usn: '1NX22CS004',
    studentName: 'Aditi Rao',
    courseCode: 'CS201',
    seatPosition: 'Row 1, Col 2',
    isQrVerified: true,
    isBiometricMatched: true,
    status: StudentAttendanceStatus.present,
    bookletBarcode: 'BC-990143',
    dummyBarcode: 'ANON-CS201-8941',
    avatarInitials: 'AR',
  ),
  StudentDeskItem(
    deskId: 'Desk B-03',
    usn: '1NX22CS009',
    studentName: 'Ananya Verma',
    courseCode: 'CS201',
    seatPosition: 'Row 1, Col 3',
    isQrVerified: false,
    isBiometricMatched: false,
    status: StudentAttendanceStatus.absent,
    avatarInitials: 'AV',
  ),
  StudentDeskItem(
    deskId: 'Desk B-04',
    usn: '1NX22CS015',
    studentName: 'Bhuvan Patel',
    courseCode: 'CS201',
    seatPosition: 'Row 2, Col 1',
    isQrVerified: true,
    isBiometricMatched: true,
    status: StudentAttendanceStatus.present,
    bookletBarcode: 'BC-990144',
    dummyBarcode: 'ANON-CS201-8942',
    avatarInitials: 'BP',
  ),
  StudentDeskItem(
    deskId: 'Desk B-05',
    usn: '1NX22CS021',
    studentName: 'Chetan Kumar',
    courseCode: 'CS201',
    seatPosition: 'Row 2, Col 2',
    isQrVerified: true,
    isBiometricMatched: true,
    status: StudentAttendanceStatus.malpractice,
    bookletBarcode: 'BC-990145',
    dummyBarcode: 'ANON-CS201-8943',
    avatarInitials: 'CK',
  ),
  StudentDeskItem(
    deskId: 'Desk B-06',
    usn: '1NX22CS028',
    studentName: 'Deepak Nair',
    courseCode: 'CS201',
    seatPosition: 'Row 2, Col 3',
    isQrVerified: true,
    isBiometricMatched: true,
    status: StudentAttendanceStatus.present,
    bookletBarcode: 'BC-990146',
    dummyBarcode: 'ANON-CS201-8944',
    avatarInitials: 'DN',
  ),
  StudentDeskItem(
    deskId: 'Desk B-07',
    usn: '1NX22CS034',
    studentName: 'Esha Gupta',
    courseCode: 'CS201',
    seatPosition: 'Row 3, Col 1',
    isQrVerified: false,
    isBiometricMatched: false,
    status: StudentAttendanceStatus.unverified,
    avatarInitials: 'EG',
  ),
  StudentDeskItem(
    deskId: 'Desk B-08',
    usn: '1NX22CS040',
    studentName: 'Farhan Ali',
    courseCode: 'CS201',
    seatPosition: 'Row 3, Col 2',
    isQrVerified: true,
    isBiometricMatched: true,
    status: StudentAttendanceStatus.present,
    bookletBarcode: 'BC-990147',
    dummyBarcode: 'ANON-CS201-8945',
    avatarInitials: 'FA',
  ),
];

final INITIAL_INCIDENTS = [
  IncidentReportItem(
    id: 'INC_01',
    deskId: 'Desk B-05',
    studentUsn: '1NX22CS021',
    studentName: 'Chetan Kumar',
    infractionType: 'Unauthorized Notes Slip',
    description: 'Found micro-chits containing binary tree algorithms hidden under calculator lid.',
    timestamp: '10:14 AM',
    isBroadcastedToCoE: true,
  ),
];

final MOCK_SESSION = InvigilatorSession(
  sessionId: 'SES-FALL26-B104',
  hallNumber: 'Exam Hall B-104 (CS Block)',
  courseCode: 'CS201',
  courseTitle: 'Data Structures & Algorithms',
  examDate: 'August 31, 2026',
  timeSlot: '09:30 AM – 12:30 PM IST',
  chiefInvigilatorName: 'Prof. Ramesh Rao',
  students: INITIAL_STUDENTS,
  incidents: INITIAL_INCIDENTS,
);
