import { SetterAssignment, QuestionPaperDraft } from './types';

export const INITIAL_ASSIGNMENTS: SetterAssignment[] = [
  {
    id: 'ASG-CS201-2026',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    department: 'Department of Computer Science & Engineering',
    semester: '3rd Semester B.Tech',
    examSession: 'Fall End-Semester 2026',
    deadline: 'October 05, 2026',
    daysRemaining: 4,
    setsRequired: 2,
    setsSubmitted: 1,
    maxMarks: 100,
    durationMinutes: 180,
    honorariumAmount: '₹8,500 ($100 USD)',
    guidelinesAcknowledged: true,
    status: 'IN_PROGRESS',
    syllabusModules: [
      { moduleNumber: 1, title: 'Asymptotic Analysis & Linear Structures', targetWeightagePercent: 20, description: 'Big-O, Omega, Theta, Stacks, Queues, Amortized Analysis' },
      { moduleNumber: 2, title: 'Hashing & Tree Structures', targetWeightagePercent: 25, description: 'Hash functions, Collisions, BST, AVL Trees, Red-Black Trees' },
      { moduleNumber: 3, title: 'Priority Queues & Graph Algorithms', targetWeightagePercent: 30, description: 'Heaps, Dijkstra, Bellman-Ford, Kruskal, Prim, Network Flow' },
      { moduleNumber: 4, title: 'Dynamic Programming & String Algorithms', targetWeightagePercent: 25, description: 'Knapsack, Matrix Chain, KMP, Tries, Suffix Automata' },
    ],
  },
  {
    id: 'ASG-CS301-2026',
    subjectCode: 'CS301',
    subjectTitle: 'Operating Systems',
    department: 'Department of Computer Science & Engineering',
    semester: '5th Semester B.Tech',
    examSession: 'Fall End-Semester 2026',
    deadline: 'October 10, 2026',
    daysRemaining: 9,
    setsRequired: 2,
    setsSubmitted: 2,
    maxMarks: 100,
    durationMinutes: 180,
    honorariumAmount: '₹8,500 ($100 USD)',
    guidelinesAcknowledged: true,
    status: 'COMPLETED',
    syllabusModules: [
      { moduleNumber: 1, title: 'Process Management & Threads', targetWeightagePercent: 25, description: 'Process lifecycle, PCB, Context Switching, POSIX threads' },
      { moduleNumber: 2, title: 'Synchronization & Deadlocks', targetWeightagePercent: 25, description: 'Semaphores, Monitors, Peterson Algorithm, Banker Algorithm' },
      { moduleNumber: 3, title: 'Memory Management & Paging', targetWeightagePercent: 25, description: 'Virtual memory, Page replacement, TLB, Inverted tables' },
      { moduleNumber: 4, title: 'Storage, File Systems & Security', targetWeightagePercent: 25, description: 'Journaling, RAID, Disk scheduling, Access control matrices' },
    ],
  },
];

export const INITIAL_DRAFTS: QuestionPaperDraft[] = [
  // CS201 - Set A (Fully Drafted & Ready)
  {
    id: 'DRAFT-CS201-SET-A',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    examSession: 'Fall 2026',
    semester: '3rd Semester B.Tech',
    setLabel: 'Set A',
    status: 'READY_FOR_SIGNING',
    totalMarks: 100,
    maxMarks: 100,
    durationMinutes: 180,
    aiQualityScore: 98,
    similarityScore: 1.2,
    lastSavedAt: 'Today at 18:40 IST',
    questions: [
      {
        id: 'q1',
        number: 1,
        section: 'Part A',
        text: 'State the formal mathematical definitions of O(g(n)), Omega(g(n)), and Theta(g(n)). Prove that 3n^2 + 5n log n = O(n^2).',
        marks: 10,
        bloomsLevel: 'Understand',
        coMapping: 'CO1',
        module: 1,
        schemeNotes: '2 marks for Big-O def, 2 for Omega, 2 for Theta, 4 marks for formal limit-based proof.'
      },
      {
        id: 'q2',
        number: 2,
        section: 'Part A',
        text: 'Compare collision resolution by Linear Probing vs Double Hashing. Explain primary and secondary clustering phenomena.',
        marks: 10,
        bloomsLevel: 'Understand',
        coMapping: 'CO2',
        module: 2,
        schemeNotes: '4 marks for collision equations, 3 marks for primary clustering, 3 marks for secondary clustering.'
      },
      {
        id: 'q3',
        number: 3,
        section: 'Part B',
        text: 'Write an algorithm for AVL tree node insertion. Illustrate double rotations (Left-Right and Right-Left) with suitable node balance factors.',
        marks: 15,
        bloomsLevel: 'Apply',
        coMapping: 'CO2',
        module: 2,
        schemeNotes: '7 marks for insertion code/pseudocode, 8 marks for LR/RL rotation diagram step-by-step.'
      },
      {
        id: 'q4',
        number: 4,
        section: 'Part B',
        text: 'Construct a Red-Black Tree for key insertions: [40, 20, 60, 10, 30, 50, 70, 25]. Clearly specify recoloring vs restructuring cases.',
        marks: 15,
        bloomsLevel: 'Apply',
        coMapping: 'CO2',
        module: 2,
        schemeNotes: 'Step-by-step tree drawings: 2 marks per critical insertion recoloring.'
      },
      {
        id: 'q5',
        number: 5,
        section: 'Part C',
        text: 'Develop Dijkstra’s Algorithm using a Binary Min-Heap priority queue. Trace the shortest path from vertex S on the provided weighted directed graph.',
        marks: 15,
        bloomsLevel: 'Analyze',
        coMapping: 'CO3',
        module: 3,
        schemeNotes: '6 marks for algorithm description, 9 marks for distance array relaxation table.'
      },
      {
        id: 'q6',
        number: 6,
        section: 'Part C',
        text: 'Formulate the 0/1 Knapsack dynamic programming recurrence. Given weights W = [2, 3, 4, 5], values V = [3, 4, 5, 6], and capacity C = 8, build the DP memoization matrix.',
        marks: 15,
        bloomsLevel: 'Evaluate',
        coMapping: 'CO4',
        module: 4,
        schemeNotes: '5 marks for DP state definition and recurrence, 10 marks for filled 2D table and backtracked items.'
      },
      {
        id: 'q7',
        number: 7,
        section: 'Part D',
        text: 'Implement the Knuth-Morris-Pratt (KMP) prefix function (Pi table). Trace string matching for pattern P = "ABABCABAB" on text T.',
        marks: 10,
        bloomsLevel: 'Apply',
        coMapping: 'CO4',
        module: 4,
        schemeNotes: '4 marks for Pi table calculation, 6 marks for state transition walkthrough.'
      },
      {
        id: 'q8',
        number: 8,
        section: 'Part D',
        text: 'Architect a Trie data structure supporting prefix autocomplete and dynamic frequency ranking for 1 million search query terms.',
        marks: 10,
        bloomsLevel: 'Create',
        coMapping: 'CO4',
        module: 4,
        schemeNotes: '5 marks for TrieNode structure, 5 marks for top-k prefix traversal logic.'
      },
    ],
  },

  // CS201 - Set B (In Progress Draft)
  {
    id: 'DRAFT-CS201-SET-B',
    subjectCode: 'CS201',
    subjectTitle: 'Data Structures & Algorithms',
    examSession: 'Fall 2026',
    semester: '3rd Semester B.Tech',
    setLabel: 'Set B',
    status: 'DRAFT',
    totalMarks: 70,
    maxMarks: 100,
    durationMinutes: 180,
    aiQualityScore: 89,
    similarityScore: 0.8,
    lastSavedAt: 'Today at 19:10 IST',
    questions: [
      {
        id: 'sb1',
        number: 1,
        section: 'Part A',
        text: 'Using Master Theorem, determine asymptotic time bounds for: (a) T(n) = 4T(n/2) + n, (b) T(n) = 2T(n/2) + n log n, (c) T(n) = 2T(n/4) + sqrt(n).',
        marks: 10,
        bloomsLevel: 'Analyze',
        coMapping: 'CO1',
        module: 1,
        schemeNotes: '3.33 marks each with explicit Master Theorem case identification.'
      },
      {
        id: 'sb2',
        number: 2,
        section: 'Part A',
        text: 'Explain Cuckoo Hashing and Hopscotch Hashing. What are their worst-case search time guarantees?',
        marks: 10,
        bloomsLevel: 'Understand',
        coMapping: 'CO2',
        module: 2,
        schemeNotes: '5 marks for Cuckoo hash tables, 5 marks for Hopscotch neighborhood bitmasks.'
      },
      {
        id: 'sb3',
        number: 3,
        section: 'Part B',
        text: 'Construct a B-Tree of order m=4 for consecutive insertions: [5, 15, 25, 35, 45, 55, 65, 75, 85]. Show all node splits.',
        marks: 15,
        bloomsLevel: 'Apply',
        coMapping: 'CO2',
        module: 2,
        schemeNotes: 'Detailed step-by-step split illustrations.'
      },
      {
        id: 'sb4',
        number: 4,
        section: 'Part B',
        text: 'Develop Tarjan’s Algorithm to find all Strongly Connected Components (SCCs) in a directed graph using DFS discovery and low-link numbers.',
        marks: 15,
        bloomsLevel: 'Analyze',
        coMapping: 'CO3',
        module: 3,
        schemeNotes: '7 marks for low-link algorithm logic, 8 marks for step-by-step graph trace.'
      },
      {
        id: 'sb5',
        number: 5,
        section: 'Part C',
        text: 'Design Bellman-Ford shortest path algorithm. Explain how it detects negative weight cycles with proof of convergence.',
        marks: 10,
        bloomsLevel: 'Analyze',
        coMapping: 'CO3',
        module: 3,
        schemeNotes: '5 marks for relaxation loop, 5 marks for |V|-th iteration negative cycle condition.'
      },
      {
        id: 'sb6',
        number: 6,
        section: 'Part C',
        text: 'Solve the Matrix Chain Multiplication problem for dimensions <10, 20, 30, 40, 30>. Find optimal parenthesization order.',
        marks: 10,
        bloomsLevel: 'Evaluate',
        coMapping: 'CO4',
        module: 4,
        schemeNotes: '5 marks for DP formula, 5 marks for m and s tables.'
      },
    ],
  },
];
