# Generated by Django 6.0.8 on 2026-08-31 05:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.UUIDField(default=uuid.uuid4, help_text='One-time token sent to the mobile app for session validation', unique=True)),
                ('geofence_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geofence_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geofence_radius_m', models.PositiveSmallIntegerField(default=200, help_text='Allowed radius in meters from the room coordinates')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CLOSED', 'Manually Closed')], db_index=True, default='PENDING', max_length=10)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scanning_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
