# Generated by Django 6.0.8 on 2026-08-31 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanning', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanningsession',
            name='invigilator',
            field=models.ForeignKey(limit_choices_to={'role': 'INVIGILATOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='scanning_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanningsession',
            name='timetable_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scanning_sessions', to='scheduling.timetableslot'),
        ),
    ]
